FloatingMeasure: CDigFloat Class Reference
CDigFloat Class Reference
CDigFloat: a class for floating point numbers which handels numerical errors of the 64 bit floating point representation.
This class offers:
#include <DigFloat.h>
Public Member Functions
CDigFloat ()
Default constructor: calls CDigFloat::_Init.
CDigFloat (const CDigFloat &other)
Copy constructor: calls CDigFloat::operator=.
CDigFloat (const double Val)
Copy constructor from double: calls DigFloat::Value.
~CDigFloat ()
CDigFloat & operator= (const CDigFloat &other)
Assignment operator:
sets from other:
CDigFloat & operator= (const double other)
Assignment operator with double:
calls CDigFloat::operator= with "other" CDigFloat constructed from double.
bool operator== (const CDigFloat &other) const
operator ==:
the absolute deviation of the comparison partners (deviation of CDigFloat::Value()) is compared to an allowed deviation range.
This deviation range depends on CDigFloat::bPrecisionActive of calling instance:
bool operator== (const double other) const
operator == with double:
calls CDigFloat::operator== with "other" CDigFloat constructed from double.
bool operator!= (const CDigFloat &other) const
operator !=:
inversion of CDigFloat::operator==
bool operator< (const CDigFloat &other) const
operator< :
bool operator<= (const CDigFloat &other) const
operator<=
bool operator>= (const CDigFloat &other) const
operator>=
bool operator> (const CDigFloat &other) const
operator>
CDigFloat & operator+= (const CDigFloat &other)
operator+=: adding CDigFloat::dValue and CDigFloat::dError (no rounding)
CDigFloat & operator-= (const CDigFloat &other)
operator-=: subtracting CDigFloat::dValue, summing CDigFloat::dError (no rounding)
CDigFloat & operator*= (const CDigFloat &other)
operator*=: multiplies CDigFloat::dValue, estimates max. from CDigFloat::dError propagated by the multiplication (no rounding)
CDigFloat & operator/= (const CDigFloat &other)
operator/=: multiplies CDigFloat::dValue, estimates max. from CDigFloat::dError propagated by the division (no rounding)
CDigFloat operator+ (const CDigFloat &other)
operator+: calls CDigFloat::operator+=
CDigFloat operator- (const CDigFloat &other)
operator-: calls CDigFloat::operator=
CDigFloat operator* (const CDigFloat &other)
operator*: calls CDigFloat::operator*=
CDigFloat operator/ (const CDigFloat &other)
operator/: calls CDigFloat::operator/=
CDigFloat & operator+= (const double other)
operator+= with double: calls CDigFloat::operator+= with CDigFloat(double)
CDigFloat & operator-= (const double other)
operator-= with double: calls CDigFloat::operator-= with "other" CDigFloat constructed from double.
CDigFloat & operator*= (const double other)
operator*= with double: calls CDigFloat::operator*= with "other" CDigFloat constructed from double.
CDigFloat & operator/= (const double other)
operator/= with double: calls CDigFloat::operator/= with "other" CDigFloat constructed from double.
CDigFloat operator+ (const double other)
operator+ with double: calls CDigFloat::operator+= with "other" CDigFloat constructed from double.
CDigFloat operator- (const double other)
operator- with double: calls CDigFloat::operator-= with "other" CDigFloat constructed from double.
CDigFloat operator* (const double other)
operator* with double: calls CDigFloat::operator*= with "other" CDigFloat constructed from double.
CDigFloat operator/ (const double other)
operator/ with double: calls CDigFloat::operator/= with "other" CDigFloat constructed from double.
void Value (const double Val)
sets CDigFloat::dValue and CDigFloat::dError corresponding to DoubleMachineEpsilon
void ResetError ()
resets CDigFloat::dError to DoubleMachineEpsilon (CDigFloat::dValue)
void SetUserDefinedError (const CDigFloat &UserDefinedError)
sets CDigFloat::dError to a user defined value. Use only if you know that your calculation errors go beyond the numerical inaccuracy for floating numbers
double Value () const
getter of CDigFloat::dValue conditionally considering CDigFloat::nPrecision:
see CDigFloat::PrecisionActive() and CDigFloat::Precision()
double RawValue () const
getter of CDigFloat::dValue (no rounding)
void RawValue (const double &other)
setter of CDigFloat::dValue (no rounding/no error setting)
double ValueMinLimit () const
getter for CDigFloat::dValue - CDigFloat::dError - (protected: for internal use only)
double ValueMaxLimit () const
getter for CDigFloat::dValue + CDigFloat::dError - (protected: for internal use only)
double Error () const
getter of CDigFloat::dError conditionally considering CDigFloat::nPrecision:
see CDigFloat::PrecisionActive() and CDigFloat::Precision()
double RawError () const
getter of CDigFloat::dError (no rounding)
int Precision () const
getter of CDigFloat::nPrecision
void Precision (const int UserPrecision)
sets CDigFloat::nPrecision and CDigFloat::dPrecisionResolution =10-nPrecision :
bool PrecisionActive () const
getter for bPrecisionActive
void PrecisionActive (const bool UserPrecisionActive)
setter for bPrecisionActive: constrols rounding to digits given by nPrecision affected functions
double PrecisionResolution () const
getter for the resolution defined by the given precision (see CDigFloat::Precision)
bool Valid ()
check if value is valid: non-NaN
string Print (bool bWithError=true) const
prints CDigFloat::dValue and conditionally CDigFloat::dError formatted according to CDigFloat::nPrecision if CDigFloat::PrecisionActive() is true. Otherwise the number of digits is formatted with DF_DEFAULT_PRINT_PRECISION.
string RawPrint (const int UserPrecision, bool bWithError=true) const
prints CDigFloat::dValue and conditionally CDigFloat::dError formatted according to UserPrecision.
string DebugOut ()
prints all members into a string for debugging purpose
Protected Member Functions
void _Init ()
initializes all members with invalid values
void Error (const double other)
setter for CDigFloat::dError (protected: for internal use only)
Protected Attributes
double dError
keeps the numerical error of CDigFloat::dValue including the propagation due to multiple operations
double dValue
the raw value
int nPrecision
number which controls the output precision of CDigFloat::dValue: affected functions
double dPrecisionResolution
the resolution which controls the output precision of CDigFloat::dValue: It is calculated by 10-nPrecision affected functions
bool bPrecisionActive
switches on (=true) / off (=false) the given precision:
affected functions
Friends
class CFloatingMeasure
CDigFloat abs (const CDigFloat &DF)
abs: returns CDigFloat with absolute value;
CDigFloat sqrt (const CDigFloat &DF)
sqrt: returns CDigFloat as square root of user given value
CDigFloat log (const CDigFloat &DF, const CDigFloat &dfBase)
log: returns CDigFloat logarithm to user given base (default: natural logarithm with base euler number);
CDigFloat pow (const CDigFloat &dfBase, const CDigFloat &dfExp)
pow: returns CDigFloat exponential expression to user given base and exponent
CDigFloat exp (const CDigFloat &dfExp)
exp: returns CDigFloat exponential expression to Euler number and user given exponent
Detailed Description
CDigFloat: a class for floating point numbers which handels numerical errors of the 64 bit floating point representation.
This class offers:
operations of floating points (+,-,/,*)
propagation of numerical errors (round-off errors) for all operations performed on an instance
setting of user defined precision for comparing and printing.
Definition at line 54 of file DigFloat.h.
Constructor & Destructor Documentation
CDigFloat() [1/3]
CDigFloat::CDigFloat ()
Default constructor: calls CDigFloat::_Init.
Definition at line 29 of file DigFloat.cpp.
References _Init().
CDigFloat() [2/3]
CDigFloat::CDigFloat (const CDigFloat & other)
Copy constructor: calls CDigFloat::operator=.
Parameters
other CDigFloat instance to copy from
Definition at line 34 of file DigFloat.cpp.
CDigFloat() [3/3]
CDigFloat::CDigFloat (const double Val)
Copy constructor from double: calls DigFloat::Value.
Parameters
Val double value
Definition at line 39 of file DigFloat.cpp.
References _Init(), and Value().
~CDigFloat()
CDigFloat::~CDigFloat ()
Destructor
Definition at line 46 of file DigFloat.cpp.
Member Function Documentation
_Init()
void CDigFloat::_Init () protected
initializes all members with invalid values
Definition at line 260 of file DigFloat.cpp.
References dError, dValue, myNAN, Precision(), and PrecisionActive().
DebugOut()
string CDigFloat::DebugOut ()
prints all members into a string for debugging purpose
Returns
string
Definition at line 284 of file DigFloat.cpp.
References Bool2String(), dError, DF_RAW_PRINT_PRECISION, dPrecisionResolution, dValue, Precision(), PrecisionActive(), Print(), RawPrint(), Round2Precision(), and Valid().
Error() [1/2]
double CDigFloat::Error () const inline
getter of CDigFloat::dError conditionally considering CDigFloat::nPrecision:
see CDigFloat::PrecisionActive() and CDigFloat::Precision()
Returns
const double
Definition at line 382 of file DigFloat.h.
References CFloatingMeasure::Precision(), CFloatingMeasure::PrecisionActive(), and Round2Precision().
Error() [2/2]
void CDigFloat::Error (const double other) inline protected
setter for CDigFloat::dError (protected: for internal use only)
Parameters
other double
Definition at line 482 of file DigFloat.h.
operator!=()
bool CDigFloat::operator!= (const CDigFloat & other) const
operator !=:
inversion of CDigFloat::operator==
Parameters
other CDigFloat to compare with
Returns
bool, true if CDigFloat::operator== is false
Definition at line 118 of file DigFloat.cpp.
References operator==().
operator*() [1/2]
CDigFloat CDigFloat::operator* (const CDigFloat & other)
operator*: calls CDigFloat::operator*=
Parameters
other CDigFloat multiplied
Returns
CDigFloat
Definition at line 180 of file DigFloat.cpp.
operator*() [2/2]
CDigFloat CDigFloat::operator* (const double other)
operator* with double: calls CDigFloat::operator*= with "other" CDigFloat constructed from double.
Parameters
other double from which "other" CDigFloat is constructed
Returns
CDigFloat
Definition at line 225 of file DigFloat.cpp.
operator*=() [1/2]
CDigFloat & CDigFloat::operator*= (const CDigFloat & other)
operator*=: multiplies CDigFloat::dValue, estimates max. from CDigFloat::dError propagated by the multiplication (no rounding)
Parameters
other CDigFloat multiplied
Returns
CDigFloat&
Definition at line 122 of file DigFloat.cpp.
References dError, dValue, RawError(), RawValue(), ValueMaxLimit(), and ValueMinLimit().
operator*=() [2/2]
CDigFloat & CDigFloat::operator*= (const double other)
operator*= with double: calls CDigFloat::operator*= with "other" CDigFloat constructed from double.
Parameters
other double from which "other" CDigFloat is constructed
Returns
CDigFloat&
Definition at line 205 of file DigFloat.cpp.
References CDigFloat(), and operator*=().
operator+() [1/2]
CDigFloat CDigFloat::operator+ (const CDigFloat & other)
operator+: calls CDigFloat::operator+=
Parameters
other CDigFloat added
Returns
CDigFloat
Definition at line 186 of file DigFloat.cpp.
operator+() [2/2]
CDigFloat CDigFloat::operator+ (const double other)
operator+ with double: calls CDigFloat::operator+= with "other" CDigFloat constructed from double.
Parameters
other double from which "other" CDigFloat is constructed
Returns
CDigFloat
Definition at line 240 of file DigFloat.cpp.
operator+=() [1/2]
CDigFloat & CDigFloat::operator+= (const CDigFloat & other)
operator+=: adding CDigFloat::dValue and CDigFloat::dError (no rounding)
Parameters
other CDigFloat added
Returns
CDigFloat&
Definition at line 158 of file DigFloat.cpp.
References dError, dValue, RawError(), and RawValue().
operator+=() [2/2]
CDigFloat & CDigFloat::operator+= (const double other)
operator+= with double: calls CDigFloat::operator+= with CDigFloat(double)
Parameters
other double added
Returns
CDigFloat
Definition at line 215 of file DigFloat.cpp.
References CDigFloat(), and operator+=().
operator-() [1/2]
CDigFloat CDigFloat::operator- (const CDigFloat & other)
operator-: calls CDigFloat::operator=
Parameters
other CDigFloat subtracted
Returns
CDigFloat
Definition at line 192 of file DigFloat.cpp.
operator-() [2/2]
CDigFloat CDigFloat::operator- (const double other)
operator- with double: calls CDigFloat::operator-= with "other" CDigFloat constructed from double.
Parameters
other double from which "other" CDigFloat is constructed
Returns
CDigFloat
Definition at line 247 of file DigFloat.cpp.
operator-=() [1/2]
CDigFloat & CDigFloat::operator-= (const CDigFloat & other)
operator-=: subtracting CDigFloat::dValue, summing CDigFloat::dError (no rounding)
Parameters
other CDigFloat subtracted
Returns
CDigFloat&
Definition at line 169 of file DigFloat.cpp.
References dError, dValue, RawError(), and RawValue().
operator-=() [2/2]
CDigFloat & CDigFloat::operator-= (const double other)
operator-= with double: calls CDigFloat::operator-= with "other" CDigFloat constructed from double.
Parameters
other double from which "other" CDigFloat is constructed
Returns
CDigFloat&
Definition at line 220 of file DigFloat.cpp.
References CDigFloat(), and operator-=().
operator/() [1/2]
CDigFloat CDigFloat::operator/ (const CDigFloat & other)
operator/: calls CDigFloat::operator/=
Parameters
other CDigFloat divided
Returns
CDigFloat
Definition at line 198 of file DigFloat.cpp.
operator/() [2/2]
CDigFloat CDigFloat::operator/ (const double other)
operator/ with double: calls CDigFloat::operator/= with "other" CDigFloat constructed from double.
Parameters
other double from which "other" CDigFloat is constructed
Returns
CDigFloat
Definition at line 233 of file DigFloat.cpp.
operator/=() [1/2]
CDigFloat & CDigFloat::operator/= (const CDigFloat & other)
operator/=: multiplies CDigFloat::dValue, estimates max. from CDigFloat::dError propagated by the division (no rounding)
Parameters
other CDigFloat divided
Returns
CDigFloat&
Definition at line 137 of file DigFloat.cpp.
References dError, dValue, myNAN, RawValue(), ValueMaxLimit(), and ValueMinLimit().
operator/=() [2/2]
CDigFloat & CDigFloat::operator/= (const double other)
operator/= with double: calls CDigFloat::operator/= with "other" CDigFloat constructed from double.
Parameters
other double from which "other" CDigFloat is constructed
Returns
CDigFloat&
Definition at line 210 of file DigFloat.cpp.
References CDigFloat(), and operator/=().
operator<()
bool CDigFloat::operator< (const CDigFloat & other) const
operator< :
Parameters
other other CDigFloat to compare with
Returns
bool, true if CDigFloat::operator!= is true AND CDigFloat::RawValue() is less than CDigFloat::RawValue() of compared instance
Definition at line 94 of file DigFloat.cpp.
References RawValue().
operator<=()
bool CDigFloat::operator<= (const CDigFloat & other) const
operator<=
Parameters
other other CDigFloat to compare with
Returns
bool, true if CDigFloat::operator== is true OR CDigFloat::RawValue() is less than CDigFloat::RawValue() of compared instance
Definition at line 101 of file DigFloat.cpp.
References RawValue().
operator=() [1/2]
CDigFloat & CDigFloat::operator= (const CDigFloat & other)
Assignment operator:
sets from other:
CDigFloat::dValue
CDigFloat::dError calling instance keeps :
CDigFloat::nPrecision
CDigFloat::bPrecisionActive
Parameters
other CDigFloat to assign from
Returns
CDigFloat&
Definition at line 51 of file DigFloat.cpp.
References dError, dValue, Precision(), PrecisionActive(), RawError(), and RawValue().
operator=() [2/2]
CDigFloat & CDigFloat::operator= (const double other)
Assignment operator with double:
calls CDigFloat::operator= with "other" CDigFloat constructed from double.
Parameters
other double from which "other" CDigFloat is constructed
Returns
CDigFloat&
Definition at line 60 of file DigFloat.cpp.
References dError, DoubleMachineEpsilon(), and dValue.
operator==() [1/2]
bool CDigFloat::operator== (const CDigFloat & other) const
operator ==:
the absolute deviation of the comparison partners (deviation of CDigFloat::Value()) is compared to an allowed deviation range.
This deviation range depends on CDigFloat::bPrecisionActive of calling instance:
true: the allowed deviation range is CDigFloat::dPrecisionResolution/2 of calling instance
false: allowed deviation range is the sum of CDigFloat::Error of the comparison partners
Parameters
other CDigFloat to compare
Returns
bool, true if absolute deviation is within the allowed deviation range
Definition at line 68 of file DigFloat.cpp.
References PrecisionActive(), PrecisionResolution(), RawError(), RawValue(), and Value().
operator==() [2/2]
bool CDigFloat::operator== (const double other) const
operator == with double:
calls CDigFloat::operator== with "other" CDigFloat constructed from double.
Parameters
other : double from which "other" CDigFloat is constructed
Returns
bool, true if absolute deviation is within the allowed deviation range
Definition at line 89 of file DigFloat.cpp.
References CDigFloat(), and operator==().
operator>()
bool CDigFloat::operator> (const CDigFloat & other) const
operator>
Parameters
other other CDigFloat to compare with
Returns
bool, true if CDigFloat::operator!= is true AND CDigFloat::RawValue() is larger than CDigFloat::RawValue() of compared instance
Definition at line 111 of file DigFloat.cpp.
References RawValue().
operator>=()
bool CDigFloat::operator>= (const CDigFloat & other) const
operator>=
Parameters
other other CDigFloat to compare with
Returns
bool, true if CDigFloat::operator== is true AND CDigFloat::RawValue() is larger than CDigFloat::RawValue() of compared instance
Definition at line 106 of file DigFloat.cpp.
References RawValue().
Precision() [1/2]
int CDigFloat::Precision () const inline
getter of CDigFloat::nPrecision
Definition at line 395 of file DigFloat.h.
Precision() [2/2]
void CDigFloat::Precision (const int UserPrecision) inline
sets CDigFloat::nPrecision and CDigFloat::dPrecisionResolution =10-nPrecision :
Parameters
UserPrecision int, defining the resolution of CDigFloat::dValue
Definition at line 402 of file DigFloat.h.
References pow(), and CFloatingMeasure::PrecisionActive().
PrecisionActive() [1/2]
bool CDigFloat::PrecisionActive () const inline
getter for bPrecisionActive
Returns
const bool
Definition at line 409 of file DigFloat.h.
PrecisionActive() [2/2]
void CDigFloat::PrecisionActive (const bool UserPrecisionActive) inline
setter for bPrecisionActive: constrols rounding to digits given by nPrecision affected functions
CDigFloat::Value()
CDigFloat::Print
CDigFloat::operator==
Parameters
UserPrecisionActive bool,
Definition at line 421 of file DigFloat.h.
PrecisionResolution()
double CDigFloat::PrecisionResolution () const inline
getter for the resolution defined by the given precision (see CDigFloat::Precision)
Returns
double
Definition at line 428 of file DigFloat.h.
Print()
string CDigFloat::Print (bool bWithError = true) const
prints CDigFloat::dValue and conditionally CDigFloat::dError formatted according to CDigFloat::nPrecision if CDigFloat::PrecisionActive() is true. Otherwise the number of digits is formatted with DF_DEFAULT_PRINT_PRECISION.
Parameters
bWithError if true, CDigFloat::dError is printed, too
Returns
string, formatted CDigFloat::dValue [ CDigFloat::dError] according to CDigFloat::nPrecision
Definition at line 268 of file DigFloat.cpp.
References DF_DEFAULT_PRINT_PRECISION, Precision(), PrecisionActive(), and RawPrint().
RawError()
double CDigFloat::RawError () const inline
getter of CDigFloat::dError (no rounding)
Returns
const double
Definition at line 389 of file DigFloat.h.
RawPrint()
string CDigFloat::RawPrint (const int UserPrecision, bool bWithError = true) const
prints CDigFloat::dValue and conditionally CDigFloat::dError formatted according to UserPrecision.
Parameters
UserPrecision int defining the precision
bWithError bool, switching printing of CDigFloat::dError
Returns
string, formatted CDigFloat::dValue [ CDigFloat::dError] according to UserPrecision
Definition at line 273 of file DigFloat.cpp.
References dValue, plmi, and RawError().
RawValue() [1/2]
double CDigFloat::RawValue () const inline
getter of CDigFloat::dValue (no rounding)
Returns
const double
Definition at line 355 of file DigFloat.h.
RawValue() [2/2]
void CDigFloat::RawValue (const double & other) inline
setter of CDigFloat::dValue (no rounding/no error setting)
Returns
const double
Definition at line 362 of file DigFloat.h.
ResetError()
void CDigFloat::ResetError () inline
resets CDigFloat::dError to DoubleMachineEpsilon (CDigFloat::dValue)
Definition at line 331 of file DigFloat.h.
SetUserDefinedError()
void CDigFloat::SetUserDefinedError (const CDigFloat & UserDefinedError) inline
sets CDigFloat::dError to a user defined value. Use only if you know that your calculation errors go beyond the numerical inaccuracy for floating numbers
Parameters
[in] UserDefinedError CDigFloat user-defined error
Definition at line 340 of file DigFloat.h.
References RawValue().
Valid()
bool CDigFloat::Valid () inline
check if value is valid: non-NaN
Returns
bool
Definition at line 435 of file DigFloat.h.
References CFloatingMeasure::_Init(), and CFloatingMeasure::DebugOut().
Value() [1/2]
void CDigFloat::Value (const double Val)
sets CDigFloat::dValue and CDigFloat::dError corresponding to DoubleMachineEpsilon
Parameters
Val Value to be set to
Definition at line 254 of file DigFloat.cpp.
References dError, DoubleMachineEpsilon(), and dValue.
Value() [2/2]
double CDigFloat::Value () const inline
getter of CDigFloat::dValue conditionally considering CDigFloat::nPrecision:
see CDigFloat::PrecisionActive() and CDigFloat::Precision()
Returns
const double
Definition at line 348 of file DigFloat.h.
References CFloatingMeasure::Precision(), CFloatingMeasure::PrecisionActive(), and Round2Precision().
ValueMaxLimit()
double CDigFloat::ValueMaxLimit () const inline
getter for CDigFloat::dValue + CDigFloat::dError - (protected: for internal use only)
Definition at line 374 of file DigFloat.h.
ValueMinLimit()
double CDigFloat::ValueMinLimit () const inline
getter for CDigFloat::dValue - CDigFloat::dError - (protected: for internal use only)
Definition at line 368 of file DigFloat.h.
Friends And Related Function Documentation
abs
CDigFloat abs (const CDigFloat & DF) friend
abs: returns CDigFloat with absolute value;
Parameters
FM CDigFloat
Returns
CDigFloat
Definition at line 302 of file DigFloat.cpp.
CFloatingMeasure
friend class CFloatingMeasure friend
Definition at line 63 of file DigFloat.h.
exp
CDigFloat exp (const CDigFloat & dfExp) friend
exp: returns CDigFloat exponential expression to Euler number and user given exponent
Parameters
dfExp CDigFloat as exponent
Returns
CDigFloat
Definition at line 392 of file DigFloat.cpp.
log
CDigFloat log (const CDigFloat & DF, const CDigFloat & dfBase) friend
log: returns CDigFloat logarithm to user given base (default: natural logarithm with base euler number);
Parameters
DF CDigFloat
dfBase CDigFloat as base (optional)
Returns
CDigFloat
Definition at line 309 of file DigFloat.cpp.
pow
CDigFloat pow (const CDigFloat & dfBase, const CDigFloat & dfExp) friend
pow: returns CDigFloat exponential expression to user given base and exponent
Parameters
dfBase CDigFloat as base
dfExp CDigFloat as exponent
Returns
CDigFloat
Definition at line 373 of file DigFloat.cpp.
sqrt
CDigFloat sqrt (const CDigFloat & DF) friend
sqrt: returns CDigFloat as square root of user given value
Parameters
DF CDigFloat
Returns
CDigFloat
Definition at line 410 of file DigFloat.cpp.
Member Data Documentation
bPrecisionActive
bool CDigFloat::bPrecisionActive protected
switches on (=true) / off (=false) the given precision:
affected functions
CDigFloat::Value()
CDigFloat::operator==
Definition at line 526 of file DigFloat.h.
dError
double CDigFloat::dError protected
keeps the numerical error of CDigFloat::dValue including the propagation due to multiple operations
Definition at line 493 of file DigFloat.h.
dPrecisionResolution
double CDigFloat::dPrecisionResolution protected
the resolution which controls the output precision of CDigFloat::dValue: It is calculated by 10-nPrecision affected functions
CDigFloat::Value() (if CDigFloat::bPrecisionActive == true)
CDigFloat::Print
CDigFloat::operator== (if CDigFloat::bPrecisionActive == true)
Definition at line 518 of file DigFloat.h.
dValue
double CDigFloat::dValue protected
the raw value
Definition at line 498 of file DigFloat.h.
nPrecision
int CDigFloat::nPrecision protected
number which controls the output precision of CDigFloat::dValue: affected functions
CDigFloat::Value() (if CDigFloat::bPrecisionActive == true)
CDigFloat::Print
CDigFloat::operator== (if CDigFloat::bPrecisionActive == true)
Definition at line 508 of file DigFloat.h.
The documentation for this class was generated from the following files:
FloatingMeasure/DigFloat/DigFloat.h
FloatingMeasure/DigFloat/DigFloat.cpp