FloatingMeasure: CBaseMeasure Class Reference
CBaseMeasure Class Reference
CBaseMeasure: represents the base-measure part of a measure.
For example milli degree celsius consists of the base-measure part "degree celsius" (see CBaseMeasure) and the pre-measure part "milli" (see CPreMeasure).
This class handles vectors of:
#include <BaseMeasure.h>
Public Member Functions
CBaseMeasure ()
default constructor:
initialize all member vectors
~CBaseMeasure ()
destructor: clears all member vectors
const double Offset (unsigned int BaseMeasureEnum)
returns the offset for the converstion to the SI measure for the given eBaseMeasure
eBaseMeasure SIID (const eBaseMeasure BaseMeasureEnum)
returns the eBaseMeasure of the SI measure for the given eBaseMeasure
const string DebugOut (const eBaseMeasure BaseMeasureEnum)
output for debugging purpose for given index
eBaseMeasure GetIDByShortLabel (const string &strShortLabel)
returns the enum (index) of the base measure by searching the vstrShort->.
eBaseMeasure GetIDByLongLabel (const string &strLongLabel)
returns the enum (index) of the base measure by searching the vstrLong
Public Member Functions inherited from CVectorHandle
CVectorHandle ()
does nothing
~CVectorHandle ()
destructor: calls CVectorHandle::_DeInit()
int GetIndexByShortLabel (const string &strShortLabel)
returns the index of the pre-unit if the user given string matches one of the elemens in CPreUnit::m_vstrPreUnitShort
int GetIndexByLongLabel (const string &strLongLabel)
returns the index of the pre-unit if the user given string matches one of the elemens in CPreUnit::m_vstrPreUnitLong
const string & Long (const unsigned int uiIndex)
gets element from CVectorHandle::vstrShort by index
const string & Short (const unsigned int uiIndex)
gets element from CVectorHandle::vstrLong by index
const double Factor (const unsigned int uiIndex)
gets element from CVectorHandle::vdFactor by index
Public Attributes
vector< int > * vnSIIndex
keeps the index of the corresponding SI unit: is its own unit in case it is the SI unit itself
vector< double > * vdOffset
keeps the offset for the conversion to the SI Unit
Additional Inherited Members
Protected Attributes inherited from CVectorHandle
vector< double > * vdFactor
vector keeping all the factors:
e.g.
vector< string > * vstrLong
vector keeping the long label
e.g.
vector< string > * vstrShort
vector keeping the short label:
e.g.
Detailed Description
CBaseMeasure: represents the base-measure part of a measure.
For example milli degree celsius consists of the base-measure part "degree celsius" (see CBaseMeasure) and the pre-measure part "milli" (see CPreMeasure).
This class handles vectors of:
SI index (e.g. for bmDegCelsius the SI index is bmDegKelvin)
base-measure factor (e.g. for °F with index bmDegFahrenheit the factor for the conversion to the SI measure °K with index bmDegKelvin is 5/9)
base-measure offset (e.g. for °C with index bmDegCelsius the offset for the conversion to the SI measure °K with index bmDegKelvin is 273.15°K)
the short label (e.g. for Volt with the index bmVolt the short label is "V")
the long label (e.g. for Volt with the index bmVolt the short label is "volt")
These vectors are accessed by the indices defined by the enum eBaseMeasure.
Definition at line 72 of file BaseMeasure.h.
Constructor & Destructor Documentation
CBaseMeasure()
CBaseMeasure::CBaseMeasure ()
default constructor:
initialize all member vectors
initializes all relevant vectors describing a unit
CBaseMeasure::vstrShort
CBaseMeasure::vstrLong
CBaseMeasure::vnSIIndex
CBaseMeasure::vdOffset
CBaseMeasure::vdFactor
Definition at line 31 of file BaseMeasure.cpp.
References bmAmpere, bmDay, bmDegCelsius, bmDegFahrenheit, bmDegKelvin, bmFarad, bmFoot, bmHertz, bmHour, bmInch, bmLast, bmMeter, bmMile, bmMinute, bmNumber, bmOhm, bmSecond, bmUnknown, bmVolt, bmYard, Omega, UNKNOWN_INDEX, UNKNOWN_LONG, UNKNOWN_SHORT, UNKNOWN_VALUE, CVectorHandle::vdFactor, vdOffset, vnSIIndex, CVectorHandle::vstrLong, and CVectorHandle::vstrShort.
~CBaseMeasure()
CBaseMeasure::~CBaseMeasure ()
destructor: clears all member vectors
CBaseMeasure::vstrShort
CBaseMeasure::vstrLong
CBaseMeasure::vnSIIndex
CBaseMeasure::vdOffset
CBaseMeasure::vdFactor clears all member vectors
Definition at line 159 of file BaseMeasure.cpp.
References vdOffset, and vnSIIndex.
Member Function Documentation
DebugOut()
const string CBaseMeasure::DebugOut (const eBaseMeasure BaseMeasureEnum)
output for debugging purpose for given index
Parameters
BaseMeasureEnum index of base measure
Returns
const string
Definition at line 165 of file BaseMeasure.cpp.
References CVectorHandle::Factor(), CVectorHandle::Long(), Offset(), CVectorHandle::Short(), and SIID().
GetIDByLongLabel()
eBaseMeasure CBaseMeasure::GetIDByLongLabel (const string & strLongLabel) inline
returns the enum (index) of the base measure by searching the vstrLong
Parameters
strLongLabel
Returns
eBaseMeasure
Definition at line 150 of file BaseMeasure.h.
References CVectorHandle::GetIndexByLongLabel().
GetIDByShortLabel()
eBaseMeasure CBaseMeasure::GetIDByShortLabel (const string & strShortLabel) inline
returns the enum (index) of the base measure by searching the vstrShort->.
Parameters
strShortLabel short label of the base measure (e.g. "V")
Returns
eBaseMeasure: the base-measure index (e.g. eBaseMeasure::bmVolt)
Definition at line 139 of file BaseMeasure.h.
References CVectorHandle::GetIndexByShortLabel().
Offset()
const double CBaseMeasure::Offset (unsigned int BaseMeasureEnum) inline
returns the offset for the converstion to the SI measure for the given eBaseMeasure
Parameters
BaseMeasureEnum index of the
Returns
const double
Definition at line 108 of file BaseMeasure.h.
References GetElementFromVectorByIndex().
SIID()
eBaseMeasure CBaseMeasure::SIID (const eBaseMeasure BaseMeasureEnum) inline
returns the eBaseMeasure of the SI measure for the given eBaseMeasure
Parameters
BaseMeasureEnum p_BaseMeasureEnum:...
Returns
eBaseMeasure
Definition at line 119 of file BaseMeasure.h.
References GetElementFromVectorByIndex().
Member Data Documentation
vdOffset
vector<double>* CBaseMeasure::vdOffset
keeps the offset for the conversion to the SI Unit
Definition at line 165 of file BaseMeasure.h.
vnSIIndex
vector<int>* CBaseMeasure::vnSIIndex
keeps the index of the corresponding SI unit: is its own unit in case it is the SI unit itself
Definition at line 159 of file BaseMeasure.h.
The documentation for this class was generated from the following files:
FloatingMeasure/Measure/BaseMeasure.h
FloatingMeasure/Measure/BaseMeasure.cpp