FloatingMeasure: CComplexMeasure Class Reference
CComplexMeasure Class Reference
CComplexMeasure: represents a list of measures (i.e. CSimpleMeasure) chained by operators * and /
This class handles:
#include <ComplexMeasure.h>
Public Member Functions
CComplexMeasure ()
CComplexMeasure (const CComplexMeasure &other)
Copy constructor: calls CComplexMeasure::
calls CComplexMeasure::_Init, newly allocates CComplexMeasure::pMeasureLeft and CComplexMeasure::pMeasureRight from "other" CComplexMeasure.
CComplexMeasure (const ePreMeasure PreMeasureEnum, const eBaseMeasure BaseMeasureEnum)
Constructor by ePreMeasure index and eBaseMeasure index:
only sets ::pMeasureLeft and deletes ::pMeasureRight.
CComplexMeasure (const CComplexMeasure *other)
Copy constructor with pointer arg. :
calls CComplexMeasure::_Init, newly allocates CComplexMeasure::pMeasureLeft and CComplexMeasure::pMeasureRight from "other" CComplexMeasure.
~CComplexMeasure ()
CComplexMeasure & operator= (const CComplexMeasure &other)
assignment operator:
CComplexMeasure & operator*= (const CComplexMeasure &other)
operator *=: calls CComplexMeasure::_AllocateLastUnsetMeasureRight
CComplexMeasure & operator/= (const CComplexMeasure &other)
operator /=: calls CComplexMeasure::_AllocateLastUnsetMeasureRight
CComplexMeasure operator* (const CComplexMeasure &other)
operator *: calls CComplexMeasure::operator*= with a copy of calling instance
CComplexMeasure operator/ (const CComplexMeasure &other)
operator /: calls CComplexMeasure::operator/= with a copy of calling instance
bool operator== (const CComplexMeasure &other) const
bool operator!= (const CComplexMeasure &other) const
bool Compatible (const CComplexMeasure &other) const
checks for a CComplexMeasure being scaled (i.e. f* this) to this
void ScaleTo (const CComplexMeasure &other)
scale to other compatible CComplexMeasure
void SetByID (const ePreMeasure PreMeasureEnum, const eBaseMeasure BaseMeasureEnum)
sets the pMeasureLeft calling CSimpleMeasure::SetByID
void Normalize ()
sets all measures to SI and calculates SIpremeasure and dSIFactor: calls internal function CComplexMeasure::_Normalize(nullptr,nullptr)
const CDigFloat & CMFactor ()
getter for dfCMFactor
const int CMExp10 ()
getter for nCMExp10
void Simplify ()
simplifies complex measure (e.g. uV / mV * A = A (exp10 += -3)) the factors of the premeasures are collected in the CComplexMeasure::nExp10 member of this class
bool Valid ()
check for valid measures: if one invalid measure is found –> everything is invalid
string OPShort ()
prints the short label of the CComplexMeasure::opEnum
string Short ()
prints the premeasure and the base measure short labels
string DebugOut ()
prints all members: can be applied for debugging purpose
Protected Member Functions
void _Init (bool bAllocateMeasureLeft=true)
void _InvertOP ()
void _AllocateLastUnsetMeasureRight (CComplexMeasure &cmOperandLeft, const CComplexMeasure &cmOperandRight, const eOperation OperationEnum)
helping function allocating the last pMeasureRight, joining with given operation
void _Normalize (eOperation *&pPreviousOP, int *&pdTempPreMeasureExp10Collector, CDigFloat *&pdTempCMFactorCollector, CComplexMeasure *&pFirstComplexMeasure)
internally called function: called by CComplexMeasure::Normalize which sets all measures to SI and calculates SIpremeasure and dSIFactor
void _COllectCMExp10CMFactorWrapper ()
this function must always called when two CComplexMeasures are joined (e.g. from function _AllocateLastUnsetMeasureRight)
void _COllectCMExp10CMFactor (eOperation *&pPreviousOP, int *&pdTempPreMeasureExp10Collector, CDigFloat *&pdTempCMFactorCollector, CComplexMeasure *&pFirstComplexMeasure)
internal function called by every function which extents CComplexMeasure with "other" CComplexMeasure collects the CMExp10 and CMFactor from "other" and unites it into the primary CMFactor and CMExp10
void _CollectLeftSortByOp (map< eOperation, CComplexMeasure *> &mOpMeas)
collects pMeasureLeft with operands into mOpMeas –> used for CComplexMeasure::Simplify
void _SearchAndShortenSameSIIndex (CComplexMeasure *pShortenPartner, eOperation &eOPofShortenPartner, eOperation &eOPofConsecutiveShortenPartner)
searches CSimpleMeasure of consecutive pMeasureRight, which pMeasureLeft have thesame SI index as pMeasureLeft of pShortenPartner: stops if the first item is found, CComplexMeasure::_ResolveMeasureLeft for pShortenPartner and the found item is called. This function is called as one step CComplexMeasure::Simplify
void _ResolveMeasureLeft ()
collects premeasure factor in nExp10 and sets pMeasureLeft to (pmIdent, bmNumber)
void _RemoveNeutralNumbers (CComplexMeasure &PreviousComplexMeasure)
void _Simplify (eOperation &PreviousOP)
void _Valid (bool &bValid)
recursive call of checking the pMeasureLeft measures being valid
const double ReleaseExp10AndFactor ()
returns the product of dfCMFactor and pow(10,Exp10()) and resets factor to 1 and nExp10 to 0
void CMExp10 (const int OtherExp10)
protected setter of nCMExp10 ... for internal use only
void CMFactor (const double Factor)
protected setter of dfCMFactor ... for internal use only
Protected Attributes
eOperation opEnum
index of the corresponding operator of pMeasureLeft and pMeasureRight
CComplexMeasure * pMeasureRight
right operand as complex measure (pointing to next pMeasureLeft, operator, and pMeasureRight for a daisy chained list of complex measures
CSimpleMeasure * pMeasureLeft
left operand is a SimpleMeasure representant
int nCMExp10
the epx10 which will be set e.g. for normalization or simplification collecting all Exp10 of PreMeasureEnum(see CComplexMeasure::Simplify() and CComplexMeasure::Normalize().)
CDigFloat dfCMFactor
the factor value which will be set e.g. for normalization or simplification collecting all SI factors(see CComplexMeasure::Simplify() and CComplexMeasure::Normalize().)
Friends
class CFloatingMeasure
class CSimpleMeasure
Detailed Description
CComplexMeasure: represents a list of measures (i.e. CSimpleMeasure) chained by operators * and /
This class handles:
operators and constructors for construction of complex measures (e.g. mV / kA)
simplification (e.g. V * A / V –> A)
normalization (e.g. mV V)
comparison (e.g. mV / mA is equal to kV / kA)
compatibility check (e.g. mV /kA is compatible with kA / mV)
REMARK: physical laws like the Ohm law is NOT (yet) meant to (and may be never will)
be considered within this class (i.e. ohm = volt / ampere)
Definition at line 49 of file ComplexMeasure.h.
Constructor & Destructor Documentation
CComplexMeasure() [1/4]
CComplexMeasure::CComplexMeasure ()
Default constructor: calls CComplexMeasure::_Init()
Definition at line 27 of file ComplexMeasure.cpp.
References _Init().
CComplexMeasure() [2/4]
CComplexMeasure::CComplexMeasure (const CComplexMeasure & other)
Copy constructor: calls CComplexMeasure::
calls CComplexMeasure::_Init, newly allocates CComplexMeasure::pMeasureLeft and CComplexMeasure::pMeasureRight from "other" CComplexMeasure.
Copy constructor:
calls CComplexMeasure::_Init, newly allocates CComplexMeasure::pMeasureLeft and CComplexMeasure::pMeasureRight from "other" CComplexMeasure
Parameters
other CComplexMeasure to
other CComplexMeasure& to copy from
Definition at line 32 of file ComplexMeasure.cpp.
References _Init(), CComplexMeasure(), CSimpleMeasure, dfCMFactor, nCMExp10, opEnum, pMeasureLeft, and pMeasureRight.
CComplexMeasure() [3/4]
CComplexMeasure::CComplexMeasure (const ePreMeasure PreMeasureEnum, const eBaseMeasure BaseMeasureEnum)
Constructor by ePreMeasure index and eBaseMeasure index:
only sets ::pMeasureLeft and deletes ::pMeasureRight.
Parameters
PreMeasureEnum pre-measure index
BaseMeasureEnum base-measure index
Definition at line 66 of file ComplexMeasure.cpp.
References _Init(), pMeasureLeft, and CSimpleMeasure::SetByID().
CComplexMeasure() [4/4]
CComplexMeasure::CComplexMeasure (const CComplexMeasure * other)
Copy constructor with pointer arg. :
calls CComplexMeasure::_Init, newly allocates CComplexMeasure::pMeasureLeft and CComplexMeasure::pMeasureRight from "other" CComplexMeasure.
Parameters
other p_other:...
Definition at line 50 of file ComplexMeasure.cpp.
References _Init(), CComplexMeasure(), CSimpleMeasure, dfCMFactor, nCMExp10, opEnum, pMeasureLeft, and pMeasureRight.
~CComplexMeasure()
CComplexMeasure::~CComplexMeasure ()
Destructor
Definition at line 72 of file ComplexMeasure.cpp.
References opEnum, opUnknown, pMeasureLeft, pMeasureRight, ~CComplexMeasure(), and CSimpleMeasure::~CSimpleMeasure().
Member Function Documentation
_AllocateLastUnsetMeasureRight()
void CComplexMeasure::_AllocateLastUnsetMeasureRight (CComplexMeasure & cmOperandLeft, const CComplexMeasure & cmOperandRight, const eOperation OperationEnum) protected
helping function allocating the last pMeasureRight, joining with given operation
Parameters
cmOperandLeft CComplexMeasure left operand
cmOperandRight CComplexMeasure right operand
OperationEnum eOperation operation
Definition at line 201 of file ComplexMeasure.cpp.
References _COllectCMExp10CMFactorWrapper(), _InvertOP(), CComplexMeasure(), opDivide, opEnum, and pMeasureRight.
_COllectCMExp10CMFactor()
void CComplexMeasure::_COllectCMExp10CMFactor (eOperation *& pPreviousOP, int *& pdTempPreMeasureExp10Collector, CDigFloat *& pdTempCMFactorCollector, CComplexMeasure *& pFirstComplexMeasure) protected
internal function called by every function which extents CComplexMeasure with "other" CComplexMeasure collects the CMExp10 and CMFactor from "other" and unites it into the primary CMFactor and CMExp10
Parameters
pPreviousOP eOperation operation of previous CComplexMeasure
pdTempPreMeasureExp10Collector int pointer collecting all exp10
pdTempCMFactorCollector CDigFloat pointer collecting all CComplexMeasure::CMFactor
pFirstComplexMeasure CComplexMeasure first complex measure where collected exp10 and CMFactor are stored
Definition at line 407 of file ComplexMeasure.cpp.
References _COllectCMExp10CMFactor(), CMExp10(), CMFactor(), dfCMFactor, opDivide, opEnum, opMult, pMeasureRight, SecureDeleteObjectPointer(), and SecureDeleteVectorPointer().
_COllectCMExp10CMFactorWrapper()
void CComplexMeasure::_COllectCMExp10CMFactorWrapper () protected
this function must always called when two CComplexMeasures are joined (e.g. from function _AllocateLastUnsetMeasureRight)
Definition at line 394 of file ComplexMeasure.cpp.
References _COllectCMExp10CMFactor().
_CollectLeftSortByOp()
void CComplexMeasure::_CollectLeftSortByOp (map< eOperation, CComplexMeasure *> & mOpMeas) protected
collects pMeasureLeft with operands into mOpMeas –> used for CComplexMeasure::Simplify
Parameters
mOpMeas p_mOpMeas:...
Definition at line 632 of file ComplexMeasure.cpp.
References _CollectLeftSortByOp(), opEnum, and pMeasureRight.
_Init()
void CComplexMeasure::_Init (bool bAllocateMeasureLeft = true) protected
Definition at line 189 of file ComplexMeasure.cpp.
References CSimpleMeasure, dfCMFactor, nCMExp10, opEnum, opUnknown, pMeasureLeft, and pMeasureRight.
_InvertOP()
void CComplexMeasure::_InvertOP () protected
Definition at line 223 of file ComplexMeasure.cpp.
References Invert(), opEnum, and pMeasureRight.
_Normalize()
void CComplexMeasure::_Normalize (eOperation *& pPreviousOP, int *& pdTempPreMeasureExp10Collector, CDigFloat *& pdTempCMFactorCollector, CComplexMeasure *& pFirstComplexMeasure) protected
internally called function: called by CComplexMeasure::Normalize which sets all measures to SI and calculates SIpremeasure and dSIFactor
setting to SI measure can only be done for factors only. Any measure which must be calculated with a non-zero offset to its SI measure is left as is. But all premeasures will be collected in eSIPreMeasure and set to identity.
Parameters
pPreviousOP eOperation operation of previous CComplexMeasure
pdTempPreMeasureExp10Collector int pointer collecting all exp10
pdTempCMFactorCollector CDigFloat pointer collecting all CComplexMeasure::CMFactor
pFirstComplexMeasure CComplexMeasure first complex measure where collected exp10 and CMFactor are stored
Definition at line 265 of file ComplexMeasure.cpp.
References _Normalize(), BASE, CSimpleMeasure::BaseID(), CMExp10(), CMFactor(), dfCMFactor, nCMExp10, opDivide, opEnum, opMult, pMeasureLeft, pMeasureRight, pmIdent, PRE, CSimpleMeasure::PreID(), SecureDeleteObjectPointer(), SecureDeleteVectorPointer(), and CSimpleMeasure::SetByID().
_RemoveNeutralNumbers()
void CComplexMeasure::_RemoveNeutralNumbers (CComplexMeasure & PreviousComplexMeasure) protected
Definition at line 557 of file ComplexMeasure.cpp.
References _RemoveNeutralNumbers(), CSimpleMeasure::BaseID(), bmNumber, opEnum, opUnknown, pMeasureLeft, pMeasureRight, pmIdent, CSimpleMeasure::PreID(), and SecureDeleteObjectPointer().
_ResolveMeasureLeft()
void CComplexMeasure::_ResolveMeasureLeft () protected
collects premeasure factor in nExp10 and sets pMeasureLeft to (pmIdent, bmNumber)
Definition at line 620 of file ComplexMeasure.cpp.
References BASE, CSimpleMeasure::BaseID(), bmNumber, dfCMFactor, nCMExp10, pMeasureLeft, pmIdent, PRE, CSimpleMeasure::PreID(), and CSimpleMeasure::SetByID().
_SearchAndShortenSameSIIndex()
void CComplexMeasure::_SearchAndShortenSameSIIndex (CComplexMeasure * pShortenPartner, eOperation & eOPofShortenPartner, eOperation & eOPofConsecutiveShortenPartner) protected
searches CSimpleMeasure of consecutive pMeasureRight, which pMeasureLeft have thesame SI index as pMeasureLeft of pShortenPartner: stops if the first item is found, CComplexMeasure::_ResolveMeasureLeft for pShortenPartner and the found item is called. This function is called as one step CComplexMeasure::Simplify
Parameters
pShortenPartner the shorten partner which lets its pMeasureRight call this function
eOPofShortenPartner the operator which preceedes the pMeasureRight of the shorten partner
eOPofConsecutiveShortenPartner
Definition at line 585 of file ComplexMeasure.cpp.
References _ResolveMeasureLeft(), _SearchAndShortenSameSIIndex(), BASE, CSimpleMeasure::BaseID(), bmNumber, opEnum, pMeasureLeft, and pMeasureRight.
_Simplify()
void CComplexMeasure::_Simplify (eOperation & PreviousOP) protected
Definition at line 537 of file ComplexMeasure.cpp.
References _SearchAndShortenSameSIIndex(), _Simplify(), opEnum, and pMeasureRight.
_Valid()
void CComplexMeasure::_Valid (bool & bValid) protected
recursive call of checking the pMeasureLeft measures being valid
Parameters
bValid bool which will be set to pMeasureLeft::Valid
Definition at line 678 of file ComplexMeasure.cpp.
References _Valid(), pMeasureLeft, pMeasureRight, and CSimpleMeasure::Valid().
CMExp10() [1/2]
const int CComplexMeasure::CMExp10 () inline
getter for nCMExp10
Returns
ePreMeasure&
Definition at line 185 of file ComplexMeasure.h.
References CSimpleMeasure::Valid().
CMExp10() [2/2]
void CComplexMeasure::CMExp10 (const int OtherExp10) inline protected
protected setter of nCMExp10 ... for internal use only
Parameters
OtherExp10 :ePreMeasure
Definition at line 317 of file ComplexMeasure.h.
CMFactor() [1/2]
const CDigFloat& CComplexMeasure::CMFactor () inline
getter for dfCMFactor
Returns
double&
Definition at line 179 of file ComplexMeasure.h.
CMFactor() [2/2]
void CComplexMeasure::CMFactor (const double Factor) inline protected
protected setter of dfCMFactor ... for internal use only
Parameters
Factor p_Factor:double
Definition at line 324 of file ComplexMeasure.h.
Compatible()
bool CComplexMeasure::Compatible (const CComplexMeasure & other) const
checks for a CComplexMeasure being scaled (i.e. f* this) to this
Parameters
other p_other:CComplexMeasure
Returns
bool
Definition at line 166 of file ComplexMeasure.cpp.
References CSimpleMeasure::BaseID(), bmNumber, Normalize(), pMeasureLeft, pMeasureRight, and Simplify().
DebugOut()
string CComplexMeasure::DebugOut ()
prints all members: can be applied for debugging purpose
Returns
string
Definition at line 702 of file ComplexMeasure.cpp.
References Bool2String(), CMExp10(), CMFactor(), DebugOut(), OPShort(), pMeasureLeft, pMeasureRight, CDigFloat::Print(), CSimpleMeasure::Short(), and Valid().
Normalize()
void CComplexMeasure::Normalize ()
sets all measures to SI and calculates SIpremeasure and dSIFactor: calls internal function CComplexMeasure::_Normalize(nullptr,nullptr)
Definition at line 250 of file ComplexMeasure.cpp.
References _Normalize().
operator!=()
bool CComplexMeasure::operator!= (const CComplexMeasure & other) const
Definition at line 162 of file ComplexMeasure.cpp.
operator*()
CComplexMeasure CComplexMeasure::operator* (const CComplexMeasure & other)
operator *: calls CComplexMeasure::operator*= with a copy of calling instance
Parameters
other CComplexMeasure to copy into CComplexMeasure::pMeasureRight connecting with opMult
Returns
CComplexMeasure
Definition at line 100 of file ComplexMeasure.cpp.
operator*=()
CComplexMeasure & CComplexMeasure::operator*= (const CComplexMeasure & other)
operator *=: calls CComplexMeasure::_AllocateLastUnsetMeasureRight
Parameters
other CComplexMeasure to copy into CComplexMeasure::pMeasureRight connecting with opMult
Returns
CComplexMeasure&
Definition at line 86 of file ComplexMeasure.cpp.
References _AllocateLastUnsetMeasureRight(), and opMult.
operator/()
CComplexMeasure CComplexMeasure::operator/ (const CComplexMeasure & other)
operator /: calls CComplexMeasure::operator/= with a copy of calling instance
Parameters
other CComplexMeasure to copy into CComplexMeasure::pMeasureRight connecting with opDivide
Returns
CComplexMeasure
Definition at line 106 of file ComplexMeasure.cpp.
operator/=()
CComplexMeasure & CComplexMeasure::operator/= (const CComplexMeasure & other)
operator /=: calls CComplexMeasure::_AllocateLastUnsetMeasureRight
Parameters
other CComplexMeasure to copy into CComplexMeasure::pMeasureRight connecting with opDivide
Returns
CComplexMeasure&
Definition at line 94 of file ComplexMeasure.cpp.
References _AllocateLastUnsetMeasureRight(), and opDivide.
operator=()
CComplexMeasure & CComplexMeasure::operator= (const CComplexMeasure & other)
assignment operator:
Parameters
other CComplexMeasure to copy from
Returns
CComplexMeasure&
Definition at line 113 of file ComplexMeasure.cpp.
References CComplexMeasure(), dfCMFactor, nCMExp10, opEnum, pMeasureLeft, pMeasureRight, and SecureDeleteObjectPointer().
operator==()
bool CComplexMeasure::operator== (const CComplexMeasure & other) const
Definition at line 130 of file ComplexMeasure.cpp.
References CSimpleMeasure::BaseID(), bmNumber, CMExp10(), CMFactor(), Normalize(), pMeasureLeft, pMeasureRight, ReleaseExp10AndFactor(), and Simplify().
OPShort()
string CComplexMeasure::OPShort () inline
prints the short label of the CComplexMeasure::opEnum
Returns
string
Definition at line 206 of file ComplexMeasure.h.
References CSimpleMeasure::_Init(), CSimpleMeasure::DebugOut(), CSingleton< SingletonObject >::instance(), and CSimpleMeasure::Short().
ReleaseExp10AndFactor()
const double CComplexMeasure::ReleaseExp10AndFactor () protected
returns the product of dfCMFactor and pow(10,Exp10()) and resets factor to 1 and nExp10 to 0
Returns
const double
Definition at line 690 of file ComplexMeasure.cpp.
References CMExp10(), CMFactor(), pow(), and CDigFloat::RawValue().
ScaleTo()
void CComplexMeasure::ScaleTo (const CComplexMeasure & other)
scale to other compatible CComplexMeasure
Parameters
other p_other:CComplexMeasure
Definition at line 644 of file ComplexMeasure.cpp.
References _Init(), CMExp10(), CMFactor(), Compatible(), dfCMFactor, nCMExp10, and Simplify().
SetByID()
void CComplexMeasure::SetByID (const ePreMeasure PreMeasureEnum, const eBaseMeasure BaseMeasureEnum)
sets the pMeasureLeft calling CSimpleMeasure::SetByID
Parameters
PreMeasureEnum p_PreMeasureEnum: index of premeasure...
BaseMeasureEnum p_BaseMeasureEnum: index of base measure
Definition at line 180 of file ComplexMeasure.cpp.
References _Init(), pMeasureLeft, pMeasureRight, SecureDeleteObjectPointer(), and CSimpleMeasure::SetByID().
Short()
string CComplexMeasure::Short ()
prints the premeasure and the base measure short labels
Returns
string
Definition at line 238 of file ComplexMeasure.cpp.
References OPShort(), pMeasureLeft, pMeasureRight, CSimpleMeasure::Short(), and Short().
Simplify()
void CComplexMeasure::Simplify ()
simplifies complex measure (e.g. uV / mV * A = A (exp10 += -3)) the factors of the premeasures are collected in the CComplexMeasure::nExp10 member of this class
Definition at line 501 of file ComplexMeasure.cpp.
References _COllectCMExp10CMFactorWrapper(), _RemoveNeutralNumbers(), _Simplify(), CSimpleMeasure::BaseID(), bmNumber, opEnum, opMult, opUnknown, pMeasureLeft, pMeasureRight, and SecureDeleteObjectPointer().
Valid()
bool CComplexMeasure::Valid ()
check for valid measures: if one invalid measure is found –> everything is invalid
Returns
bool
Definition at line 666 of file ComplexMeasure.cpp.
References _Valid(), pMeasureLeft, pMeasureRight, and CSimpleMeasure::Valid().
Friends And Related Function Documentation
CFloatingMeasure
friend class CFloatingMeasure friend
Definition at line 56 of file ComplexMeasure.h.
CSimpleMeasure
friend class CSimpleMeasure friend
Definition at line 57 of file ComplexMeasure.h.
Member Data Documentation
dfCMFactor
CDigFloat CComplexMeasure::dfCMFactor protected
the factor value which will be set e.g. for normalization or simplification collecting all SI factors(see CComplexMeasure::Simplify() and CComplexMeasure::Normalize().)
Definition at line 359 of file ComplexMeasure.h.
nCMExp10
int CComplexMeasure::nCMExp10 protected
the epx10 which will be set e.g. for normalization or simplification collecting all Exp10 of PreMeasureEnum(see CComplexMeasure::Simplify() and CComplexMeasure::Normalize().)
Definition at line 353 of file ComplexMeasure.h.
opEnum
eOperation CComplexMeasure::opEnum protected
index of the corresponding operator of pMeasureLeft and pMeasureRight
Definition at line 336 of file ComplexMeasure.h.
pMeasureLeft
CSimpleMeasure* CComplexMeasure::pMeasureLeft protected
left operand is a SimpleMeasure representant
Definition at line 347 of file ComplexMeasure.h.
pMeasureRight
CComplexMeasure* CComplexMeasure::pMeasureRight protected
right operand as complex measure (pointing to next pMeasureLeft, operator, and pMeasureRight for a daisy chained list of complex measures
Definition at line 342 of file ComplexMeasure.h.
The documentation for this class was generated from the following files:
FloatingMeasure/Measure/ComplexMeasure.h
FloatingMeasure/Measure/ComplexMeasure.cpp