FloatingMeasure: CVectorHandle Class Reference
CVectorHandle Class Reference
This class keeps three vectors (two string : Short and Long and one double : Factor). These vectors are common to classes CPreMeasure and CBaseMeasure and are therefore packed into this class for vector handling.
#include <VectorHandle.h>
Public Member Functions
CVectorHandle ()
does nothing
~CVectorHandle ()
destructor: calls CVectorHandle::_DeInit()
int GetIndexByShortLabel (const string &strShortLabel)
returns the index of the pre-unit if the user given string matches one of the elemens in CPreUnit::m_vstrPreUnitShort
int GetIndexByLongLabel (const string &strLongLabel)
returns the index of the pre-unit if the user given string matches one of the elemens in CPreUnit::m_vstrPreUnitLong
const string & Long (const unsigned int uiIndex)
gets element from CVectorHandle::vstrShort by index
const string & Short (const unsigned int uiIndex)
gets element from CVectorHandle::vstrLong by index
const double Factor (const unsigned int uiIndex)
gets element from CVectorHandle::vdFactor by index
Protected Attributes
vector< double > * vdFactor
vector keeping all the factors:
e.g.
vector< string > * vstrLong
vector keeping the long label
e.g.
vector< string > * vstrShort
vector keeping the short label:
e.g.
Detailed Description
This class keeps three vectors (two string : Short and Long and one double : Factor). These vectors are common to classes CPreMeasure and CBaseMeasure and are therefore packed into this class for vector handling.
Definition at line 37 of file VectorHandle.h.
Constructor & Destructor Documentation
CVectorHandle()
CVectorHandle::CVectorHandle ()
does nothing
Definition at line 28 of file VectorHandle.cpp.
References vdFactor, vstrLong, and vstrShort.
~CVectorHandle()
CVectorHandle::~CVectorHandle ()
destructor: calls CVectorHandle::_DeInit()
Definition at line 36 of file VectorHandle.cpp.
References SecureDeleteObjectPointer(), vdFactor, vstrLong, and vstrShort.
Member Function Documentation
Factor()
const double CVectorHandle::Factor (const unsigned int uiIndex) inline
gets element from CVectorHandle::vdFactor by index
Parameters
uiIndex index
Returns
double: factor
Definition at line 116 of file VectorHandle.h.
References GetElementFromVectorByIndex().
GetIndexByLongLabel()
int CVectorHandle::GetIndexByLongLabel (const string & strLongLabel) inline
returns the index of the pre-unit if the user given string matches one of the elemens in CPreUnit::m_vstrPreUnitLong
Parameters
strLongLabel p_strPreUnitLongLabel: user given long label of the demanded unit
Returns
const unsigned int&
Definition at line 80 of file VectorHandle.h.
References FindElementInVectorGetIndex().
GetIndexByShortLabel()
int CVectorHandle::GetIndexByShortLabel (const string & strShortLabel) inline
returns the index of the pre-unit if the user given string matches one of the elemens in CPreUnit::m_vstrPreUnitShort
Parameters
strShortLabel p_strPreUnitShortLabel:user given short label of the demanded unit
Returns
const unsigned int&
Definition at line 69 of file VectorHandle.h.
References FindElementInVectorGetIndex().
Long()
const string& CVectorHandle::Long (const unsigned int uiIndex) inline
gets element from CVectorHandle::vstrShort by index
Parameters
uiIndex index
Returns
string: long label
Definition at line 94 of file VectorHandle.h.
References GetElementFromVectorByIndex().
Short()
const string& CVectorHandle::Short (const unsigned int uiIndex) inline
gets element from CVectorHandle::vstrLong by index
Parameters
uiIndex index
Returns
string: short label
Definition at line 105 of file VectorHandle.h.
References GetElementFromVectorByIndex().
Member Data Documentation
vdFactor
vector<double>* CVectorHandle::vdFactor protected
vector keeping all the factors:
e.g.
CPreMeasure: milli –> 0.001
CBaseMeasure: °F –> 5/9 (SI recalculation factor for °K)
Definition at line 136 of file VectorHandle.h.
vstrLong
vector<string>* CVectorHandle::vstrLong protected
vector keeping the long label
e.g.
CPreMeasure: milli –> "milli"
CBaseMeasure: volt –> "volt"
Definition at line 145 of file VectorHandle.h.
vstrShort
vector<string>* CVectorHandle::vstrShort protected
vector keeping the short label:
e.g.
CPreMeasure: milli –> "m"
CBaseMeasure: volt –> "V"
Definition at line 154 of file VectorHandle.h.
The documentation for this class was generated from the following files:
FloatingMeasure/Measure/VectorHandle.h
FloatingMeasure/Measure/VectorHandle.cpp