FloatingMeasure: FloatingMeasure/FloatingMeasure/FloatingMeasure.h File Reference
FloatingMeasure.h File Reference
#include <Measure/ComplexMeasure.h>
#include <iostream>
Classes
class CFloatingMeasure
FloatingMeasure: represents a floating number with a complex measure (e.g. 10*m/s). This class offers:
Functions
CFloatingMeasure abs (const CFloatingMeasure &FM)
abs: returns CFloatingMeasure with absolute value;
CFloatingMeasure operator* (const CDigFloat &Floating, const CComplexMeasure &Measure)
operator* : enables CFloatingMeasure = 10*mV;
CFloatingMeasure operator* (const CComplexMeasure &Measure, const CDigFloat &Floating)
operator* : enables CFloatingMeasure = mV*10;
CFloatingMeasure operator* (const CFloatingMeasure &FloatingMeasure, const CComplexMeasure &Measure)
operator* : enables CFloatingMeasure = 10*mV*uA;
CFloatingMeasure operator* (const CComplexMeasure &Measure, const CFloatingMeasure &FloatingMeasure)
operator* : enables CFloatingMeasure = mV*uA*10;
CFloatingMeasure operator/ (const CDigFloat &Floating, const CComplexMeasure &Measure)
operator/ : enables CFloatingMeasure = 10/mV;
CFloatingMeasure operator/ (const CComplexMeasure &Measure, const CDigFloat &Floating)
operator/ : enables CFloatingMeasure = mV/10;
CFloatingMeasure operator/ (const CFloatingMeasure &FloatingMeasure, const CComplexMeasure &Measure)
operator/ : enables CFloatingMeasure = 10*mV/uA;
Function Documentation
abs()
CFloatingMeasure abs (const CFloatingMeasure & FM)
abs: returns CFloatingMeasure with absolute value;
Parameters
FM CFloatingMeasure
Returns
CFloatingMeasure
Definition at line 413 of file FloatingMeasure.cpp.
References abs(), CFloatingMeasure::CFloatingMeasure(), CFloatingMeasure::Floating(), and CFloatingMeasure::Measure().
operator*() [1/4]
CFloatingMeasure operator* (const CDigFloat & Floating, const CComplexMeasure & Measure) inline
operator* : enables CFloatingMeasure = 10*mV;
Parameters
Floating CDigFloat
Measure CComplexMeasure
Returns
CFloatingMeasure
Definition at line 440 of file FloatingMeasure.h.
References CComplexMeasure::CFloatingMeasure.
operator*() [2/4]
CFloatingMeasure operator* (const CComplexMeasure & Measure, const CDigFloat & Floating) inline
operator* : enables CFloatingMeasure = mV*10;
Parameters
Measure CComplexMeasure
Floating CDigFloat
Returns
CFloatingMeasure
Definition at line 453 of file FloatingMeasure.h.
References CComplexMeasure::CFloatingMeasure.
operator*() [3/4]
CFloatingMeasure operator* (const CFloatingMeasure & FloatingMeasure, const CComplexMeasure & Measure) inline
operator* : enables CFloatingMeasure = 10*mV*uA;
Parameters
FloatingMeasure CFloatingMeasure (e.g. 10*mV)
Measure CComplexMeasure (e.g. uA)
Returns
CFloatingMeasure
Definition at line 466 of file FloatingMeasure.h.
References CComplexMeasure::CFloatingMeasure, CFloatingMeasure::Floating(), and CFloatingMeasure::Measure().
operator*() [4/4]
CFloatingMeasure operator* (const CComplexMeasure & Measure, const CFloatingMeasure & FloatingMeasure) inline
operator* : enables CFloatingMeasure = mV*uA*10;
Parameters
Measure CComplexMeasure (e.g. mV*uA)
FloatingMeasure CFloatingMeasure (e.g. 10)
Returns
CFloatingMeasure
Definition at line 479 of file FloatingMeasure.h.
References CComplexMeasure::CFloatingMeasure, CFloatingMeasure::Floating(), and CFloatingMeasure::Measure().
operator/() [1/3]
CFloatingMeasure operator/ (const CDigFloat & Floating, const CComplexMeasure & Measure) inline
operator/ : enables CFloatingMeasure = 10/mV;
Parameters
Floating CDigFloat
Measure CComplexMeasure
Returns
CFloatingMeasure
Definition at line 492 of file FloatingMeasure.h.
References bmNumber, CComplexMeasure::CComplexMeasure(), CComplexMeasure::CFloatingMeasure, and pmIdent.
operator/() [2/3]
CFloatingMeasure operator/ (const CComplexMeasure & Measure, const CDigFloat & Floating) inline
operator/ : enables CFloatingMeasure = mV/10;
Parameters
Measure CComplexMeasure
Floating CDigFloat
Returns
CFloatingMeasure
Definition at line 505 of file FloatingMeasure.h.
References bmNumber, CComplexMeasure::CComplexMeasure(), CComplexMeasure::CFloatingMeasure, and pmIdent.
operator/() [3/3]
CFloatingMeasure operator/ (const CFloatingMeasure & FloatingMeasure, const CComplexMeasure & Measure) inline
operator/ : enables CFloatingMeasure = 10*mV/uA;
Parameters
FloatingMeasure CFloatingMeasure (e.g. 10*mV)
Measure CComplexMeasure (e.g. uA)
Returns
CFloatingMeasure
Definition at line 518 of file FloatingMeasure.h.
References CComplexMeasure::CFloatingMeasure, CFloatingMeasure::Floating(), and CFloatingMeasure::Measure().