FloatingMeasure: FloatingMeasure/FloatingMeasure/FloatingMeasure.cpp File Reference
FloatingMeasure.cpp File Reference
#include "FloatingMeasure.h"
Functions
CFloatingMeasure abs (const CFloatingMeasure &FM)
abs: returns CFloatingMeasure with absolute value;
Function Documentation
abs()
CFloatingMeasure abs (const CFloatingMeasure & FM)
abs: returns CFloatingMeasure with absolute value;
Parameters
FM CFloatingMeasure
Returns
CFloatingMeasure
Definition at line 413 of file FloatingMeasure.cpp.
References abs(), CFloatingMeasure::CFloatingMeasure(), CFloatingMeasure::Floating(), and CFloatingMeasure::Measure().