FloatingMeasure: CFloatingMeasure Class Reference
CFloatingMeasure Class Reference
FloatingMeasure: represents a floating number with a complex measure (e.g. 10*m/s). This class offers:
#include <FloatingMeasure.h>
Public Member Functions
CFloatingMeasure ()
CFloatingMeasure (const CFloatingMeasure &other)
CFloatingMeasure (const CDigFloat &OtherFloating, const CComplexMeasure &OtherMeasure)
Constructor from CDigFloat and CComplexMeasure.
~CFloatingMeasure ()
CFloatingMeasure & operator= (const CFloatingMeasure &other)
bool operator== (const CFloatingMeasure &other) const
comparison operator
bool operator!= (const CFloatingMeasure &other) const
operator!=
bool operator< (const CFloatingMeasure &other) const
operator<
bool operator<= (const CFloatingMeasure &other) const
operator<=
bool operator>= (const CFloatingMeasure &other) const
operator>=
bool operator> (const CFloatingMeasure &other) const
operator>
CFloatingMeasure & operator+= (const CFloatingMeasure &other)
operator +=
CFloatingMeasure & operator-= (const CFloatingMeasure &other)
operator-=
CFloatingMeasure & operator*= (const CFloatingMeasure &other)
operator*=
CFloatingMeasure & operator/= (const CFloatingMeasure &other)
operator/=
CFloatingMeasure operator+ (const CFloatingMeasure &other)
operator +
CFloatingMeasure operator- (const CFloatingMeasure &other)
operator-
CFloatingMeasure operator* (const CFloatingMeasure &other)
operator*
CFloatingMeasure operator/ (const CFloatingMeasure &other)
operator/
CFloatingMeasure & operator*= (const double &other)
operator*=
CFloatingMeasure & operator*= (const CComplexMeasure &other)
operator*=
CFloatingMeasure & operator/= (const double &other)
operator/=
CFloatingMeasure operator* (const double &other)
operator*
CFloatingMeasure operator/ (const double &other)
operator/
void Normalize ()
convert to SI unit and remove premeasures != pmIdent
void Simplify ()
convert to SI unit and remove premeasures != pmIdent
bool Compatible (const CFloatingMeasure &other)
check measures for compatibility
bool Compatible (const CComplexMeasure &other)
check measures for compatibility
void ScaleTo (const CFloatingMeasure &other)
scales to CComplexMeasure of other
void ScaleTo (const CComplexMeasure &other)
scales to CComplexMeasure other
void Precision (const CFloatingMeasure &UserPrecision)
setting precision of floating number by floating number: calls CDigFloat::Precision(nDigits) from CFloatingMeasure::dfFloating.
void PrecisionActive (const bool bPrecisionActive)
switch precision defined by dfFloating::nPrecision on / off
const bool PrecisonActive () const
get PrecisionActive from dfFloating
bool Valid ()
checks if the cmMeasure and dfFloating are valid values
string DebugOut ()
debugging output for every member
string PrintShort ()
printing short output: e.g. "10*mv/V"
CDigFloat Floating () const
gettter for dfFloating
CComplexMeasure Measure () const
getter for cmMeasure
CFloatingMeasure Precision () const
get the precision as CFloatingMeasure
Protected Member Functions
void _Init ()
initialization with invalid values: floating = myNaN, cmMeasure = unknownn
void _Precision (const CFloatingMeasure *pOtherPrecision)
void Measure (const CComplexMeasure &other)
setter for cmMeasure
void Floating (const CDigFloat &other)
setter for dfFloating
Protected Attributes
CComplexMeasure cmMeasure
CDigFloat dfFloating
CFloatingMeasure * pfmPrecision
Friends
class CComplexMeasure
Detailed Description
FloatingMeasure: represents a floating number with a complex measure (e.g. 10*m/s). This class offers:
operators (+,-,*,/,<=, >=, ==, !=, <, >)
simplification (e.g. 1*ms*10*m/s –> 0.01m
normalization (i.e. SI units. e.g. 36*km/h –> 10*m/s)
handling of the precision of the floating part for output and calculations
Definition at line 67 of file FloatingMeasure.h.
Constructor & Destructor Documentation
CFloatingMeasure() [1/3]
CFloatingMeasure::CFloatingMeasure ()
Default constructor
Definition at line 27 of file FloatingMeasure.cpp.
References _Init().
CFloatingMeasure() [2/3]
CFloatingMeasure::CFloatingMeasure (const CFloatingMeasure & other)
Copy constructor
Parameters
other CFloatingMeasure
Definition at line 32 of file FloatingMeasure.cpp.
References _Init(), _Precision(), Floating(), Measure(), and pfmPrecision.
CFloatingMeasure() [3/3]
CFloatingMeasure::CFloatingMeasure (const CDigFloat & OtherFloating, const CComplexMeasure & OtherMeasure)
Constructor from CDigFloat and CComplexMeasure.
Parameters
OtherFloating :CDigFloat
OtherMeasure :CComplexMeasure
Definition at line 40 of file FloatingMeasure.cpp.
References _Init(), Floating(), and Measure().
~CFloatingMeasure()
CFloatingMeasure::~CFloatingMeasure ()
Destructor
Definition at line 46 of file FloatingMeasure.cpp.
References pfmPrecision, and SecureDeleteObjectPointer().
Member Function Documentation
_Init()
void CFloatingMeasure::_Init () protected
initialization with invalid values: floating = myNaN, cmMeasure = unknownn
Definition at line 354 of file FloatingMeasure.cpp.
References CComplexMeasure::_Init(), CDigFloat::_Init(), cmMeasure, dfFloating, and pfmPrecision.
_Precision()
void CFloatingMeasure::_Precision (const CFloatingMeasure * pOtherPrecision) protected
Definition at line 360 of file FloatingMeasure.cpp.
References pfmPrecision, Precision(), and SecureDeleteObjectPointer().
Compatible() [1/2]
bool CFloatingMeasure::Compatible (const CFloatingMeasure & other) inline
check measures for compatibility
Parameters
other:CFloatingMeasure
Returns
bool
Definition at line 281 of file FloatingMeasure.h.
References Measure().
Compatible() [2/2]
bool CFloatingMeasure::Compatible (const CComplexMeasure & other) inline
check measures for compatibility
Parameters
other:CComplexMeasure&
Returns
bool
Definition at line 290 of file FloatingMeasure.h.
References CComplexMeasure::ScaleTo().
DebugOut()
string CFloatingMeasure::DebugOut ()
debugging output for every member
Returns
string
Definition at line 376 of file FloatingMeasure.cpp.
References Bool2String(), cmMeasure, CComplexMeasure::DebugOut(), CDigFloat::DebugOut(), dfFloating, pfmPrecision, PrintShort(), and Valid().
Floating() [1/2]
CDigFloat CFloatingMeasure::Floating () const inline
gettter for dfFloating
Returns
CDigFloat
Definition at line 360 of file FloatingMeasure.h.
Floating() [2/2]
void CFloatingMeasure::Floating (const CDigFloat & other) inline protected
setter for dfFloating
Parameters
other:CDigFloat
Definition at line 401 of file FloatingMeasure.h.
Measure() [1/2]
CComplexMeasure CFloatingMeasure::Measure () const inline
getter for cmMeasure
Returns
CComplexMeasure
Definition at line 366 of file FloatingMeasure.h.
References CComplexMeasure::_Init().
Measure() [2/2]
void CFloatingMeasure::Measure (const CComplexMeasure & other) protected
setter for cmMeasure
Parameters
other:CComplexMeasure
Definition at line 300 of file FloatingMeasure.cpp.
References _Precision(), cmMeasure, and pfmPrecision.
Normalize()
void CFloatingMeasure::Normalize ()
convert to SI unit and remove premeasures != pmIdent
Definition at line 210 of file FloatingMeasure.cpp.
References BASE, CSimpleMeasure::BaseID(), cmMeasure, dfFloating, Measure(), CComplexMeasure::Normalize(), CComplexMeasure::pMeasureLeft, pmIdent, CComplexMeasure::ReleaseExp10AndFactor(), CSimpleMeasure::SetByID(), CSimpleMeasure::SIFactor(), and CSimpleMeasure::SIOffset().
operator!=()
bool CFloatingMeasure::operator!= (const CFloatingMeasure & other) const
operator!=
Parameters
other:CFloatingMeasure
Returns
bool
Definition at line 71 of file FloatingMeasure.cpp.
operator*() [1/2]
CFloatingMeasure CFloatingMeasure::operator* (const CFloatingMeasure & other)
operator*
Parameters
other:CFloatingMeasure
Returns
CFloatingMeasure&
Definition at line 164 of file FloatingMeasure.cpp.
operator*() [2/2]
CFloatingMeasure CFloatingMeasure::operator* (const double & other)
operator*
Parameters
other:double
Returns
CFloatingMeasure&
Definition at line 196 of file FloatingMeasure.cpp.
operator*=() [1/3]
CFloatingMeasure & CFloatingMeasure::operator*= (const CFloatingMeasure & other)
operator*=
Parameters
other:CFloatingMeasure
Returns
CFloatingMeasure&
Definition at line 136 of file FloatingMeasure.cpp.
References cmMeasure, dfFloating, Floating(), Measure(), and CComplexMeasure::ReleaseExp10AndFactor().
operator*=() [2/3]
CFloatingMeasure & CFloatingMeasure::operator*= (const double & other)
operator*=
Parameters
other:double
Returns
CFloatingMeasure&
Definition at line 178 of file FloatingMeasure.cpp.
References dfFloating.
operator*=() [3/3]
CFloatingMeasure & CFloatingMeasure::operator*= (const CComplexMeasure & other)
operator*=
Parameters
other type CComplexMeasure
Returns
CFloatingMeasure&
Definition at line 184 of file FloatingMeasure.cpp.
References cmMeasure.
operator+()
CFloatingMeasure CFloatingMeasure::operator+ (const CFloatingMeasure & other)
operator +
Parameters
other:CFloatingMeasure
Returns
CFloatingMeasure&
Definition at line 150 of file FloatingMeasure.cpp.
operator+=()
CFloatingMeasure & CFloatingMeasure::operator+= (const CFloatingMeasure & other)
operator +=
Parameters
other:CFloatingMeasure
Returns
CFloatingMeasure&
Definition at line 103 of file FloatingMeasure.cpp.
References _Init(), Compatible(), dfFloating, Floating(), and ScaleTo().
operator-()
CFloatingMeasure CFloatingMeasure::operator- (const CFloatingMeasure & other)
operator-
Parameters
other:CFloatingMeasure
Returns
CFloatingMeasure&
Definition at line 157 of file FloatingMeasure.cpp.
operator-=()
CFloatingMeasure & CFloatingMeasure::operator-= (const CFloatingMeasure & other)
operator-=
Parameters
other:CFloatingMeasure
Returns
CFloatingMeasure&
Definition at line 119 of file FloatingMeasure.cpp.
References _Init(), Compatible(), dfFloating, Floating(), and ScaleTo().
operator/() [1/2]
CFloatingMeasure CFloatingMeasure::operator/ (const CFloatingMeasure & other)
operator/
Parameters
other:CFloatingMeasure
Returns
CFloatingMeasure&
Definition at line 171 of file FloatingMeasure.cpp.
operator/() [2/2]
CFloatingMeasure CFloatingMeasure::operator/ (const double & other)
operator/
Parameters
other:double
Returns
CFloatingMeasure&
Definition at line 203 of file FloatingMeasure.cpp.
operator/=() [1/2]
CFloatingMeasure & CFloatingMeasure::operator/= (const CFloatingMeasure & other)
operator/=
Parameters
other:CFloatingMeasure
Returns
CFloatingMeasure&
Definition at line 143 of file FloatingMeasure.cpp.
References cmMeasure, dfFloating, Floating(), Measure(), and CComplexMeasure::ReleaseExp10AndFactor().
operator/=() [2/2]
CFloatingMeasure & CFloatingMeasure::operator/= (const double & other)
operator/=
Parameters
other double
Returns
CFloatingMeasure&
Definition at line 190 of file FloatingMeasure.cpp.
References dfFloating.
operator<()
bool CFloatingMeasure::operator< (const CFloatingMeasure & other) const
operator<
Parameters
other:CFloatingMeasure
Returns
bool
Definition at line 75 of file FloatingMeasure.cpp.
References Floating(), and ScaleTo().
operator<=()
bool CFloatingMeasure::operator<= (const CFloatingMeasure & other) const
operator<=
Parameters
other:CFloatingMeasure
Returns
bool
Definition at line 82 of file FloatingMeasure.cpp.
References Floating(), and ScaleTo().
operator=()
CFloatingMeasure & CFloatingMeasure::operator= (const CFloatingMeasure & other)
Assignment operator
Parameters
other CFloatingMeasure
Returns
CFloatingMeasure
Definition at line 51 of file FloatingMeasure.cpp.
References _Precision(), Floating(), Measure(), and pfmPrecision.
operator==()
bool CFloatingMeasure::operator== (const CFloatingMeasure & other) const
comparison operator
Parameters
other:CFloatingMeasure
Returns
bool
Definition at line 60 of file FloatingMeasure.cpp.
References Floating(), Measure(), and ScaleTo().
operator>()
bool CFloatingMeasure::operator> (const CFloatingMeasure & other) const
operator>
Parameters
other:CFloatingMeasure
Returns
bool
Definition at line 96 of file FloatingMeasure.cpp.
References Floating(), and ScaleTo().
operator>=()
bool CFloatingMeasure::operator>= (const CFloatingMeasure & other) const
operator>=
Parameters
other:CFloatingMeasure
Returns
bool
Definition at line 89 of file FloatingMeasure.cpp.
References Floating(), and ScaleTo().
Precision() [1/2]
void CFloatingMeasure::Precision (const CFloatingMeasure & UserPrecision)
setting precision of floating number by floating number: calls CDigFloat::Precision(nDigits) from CFloatingMeasure::dfFloating.
Parameters
UserPrecision CFloatingMeasure which determines no. of digits=(-log(UserPrecision) +1)
Definition at line 309 of file FloatingMeasure.cpp.
References CFloatingMeasure(), dfFloating, Floating(), log(), Measure(), pfmPrecision, CDigFloat::Precision(), PrecisionActive(), CDigFloat::RawError(), CDigFloat::RawValue(), ScaleTo(), and Valid().
Precision() [2/2]
CFloatingMeasure CFloatingMeasure::Precision () const
get the precision as CFloatingMeasure
Returns
CFloatingMeasure
Definition at line 346 of file FloatingMeasure.cpp.
References pfmPrecision.
PrecisionActive()
void CFloatingMeasure::PrecisionActive (const bool bPrecisionActive) inline
switch precision defined by dfFloating::nPrecision on / off
Parameters
bPrecisionActive p_bPrecisionActive:bool
Definition at line 322 of file FloatingMeasure.h.
PrecisonActive()
const bool CFloatingMeasure::PrecisonActive () const inline
get PrecisionActive from dfFloating
Returns
const bool
Definition at line 328 of file FloatingMeasure.h.
PrintShort()
string CFloatingMeasure::PrintShort ()
printing short output: e.g. "10*mv/V"
Returns
string
Definition at line 370 of file FloatingMeasure.cpp.
References cmMeasure, dfFloating, CDigFloat::Print(), and CComplexMeasure::Short().
ScaleTo() [1/2]
void CFloatingMeasure::ScaleTo (const CFloatingMeasure & other)
scales to CComplexMeasure of other
Parameters
other:CFloatingMeasure
Definition at line 286 of file FloatingMeasure.cpp.
References _Init(), cmMeasure, Compatible(), dfFloating, Measure(), CComplexMeasure::ReleaseExp10AndFactor(), and CComplexMeasure::ScaleTo().
ScaleTo() [2/2]
void CFloatingMeasure::ScaleTo (const CComplexMeasure & other)
scales to CComplexMeasure other
Parameters
other:CComplexMeasure&
Definition at line 238 of file FloatingMeasure.cpp.
References _Init(), BASE, CSimpleMeasure::BaseID(), cmMeasure, CComplexMeasure::Compatible(), Compatible(), dfFloating, Measure(), Normalize(), CComplexMeasure::pMeasureLeft, CComplexMeasure::pMeasureRight, PRE, CSimpleMeasure::PreID(), CComplexMeasure::ReleaseExp10AndFactor(), CComplexMeasure::ScaleTo(), and CSimpleMeasure::SIOffset().
Simplify()
void CFloatingMeasure::Simplify ()
convert to SI unit and remove premeasures != pmIdent
Definition at line 232 of file FloatingMeasure.cpp.
References cmMeasure, dfFloating, CComplexMeasure::ReleaseExp10AndFactor(), and CComplexMeasure::Simplify().
Valid()
bool CFloatingMeasure::Valid () inline
checks if the cmMeasure and dfFloating are valid values
Returns
bool
Definition at line 334 of file FloatingMeasure.h.
References CComplexMeasure::DebugOut().
Friends And Related Function Documentation
CComplexMeasure
friend class CComplexMeasure friend
Definition at line 73 of file FloatingMeasure.h.
Member Data Documentation
cmMeasure
CComplexMeasure CFloatingMeasure::cmMeasure protected
Definition at line 407 of file FloatingMeasure.h.
dfFloating
CDigFloat CFloatingMeasure::dfFloating protected
Definition at line 408 of file FloatingMeasure.h.
pfmPrecision
CFloatingMeasure* CFloatingMeasure::pfmPrecision protected
Definition at line 409 of file FloatingMeasure.h.
The documentation for this class was generated from the following files:
FloatingMeasure/FloatingMeasure/FloatingMeasure.h
FloatingMeasure/FloatingMeasure/FloatingMeasure.cpp