FloatingMeasure: FloatingMeasure/DigFloat/DigFloat.h File Reference
DigFloat.h File Reference
#include <Utils/Utils.h>
Classes
class CDigFloat
CDigFloat: a class for floating point numbers which handels numerical errors of the 64 bit floating point representation.
This class offers:
Macros
#define DF_RAW_PRINT_PRECISION 40
#define DF_DEFAULT_PRINT_PRECISION 10
Functions
CDigFloat abs (const CDigFloat &DF)
abs: returns CDigFloat with absolute value;
CDigFloat log (const CDigFloat &DF, const CDigFloat &dfBase=0)
log: returns CDigFloat logarithm to user given base (default: natural logarithm with base euler number);
CDigFloat pow (const CDigFloat &dfBase, const CDigFloat &dfExp)
pow: returns CDigFloat exponential expression to user given base and exponent
CDigFloat exp (const CDigFloat &dfExp)
exp: returns CDigFloat exponential expression to Euler number and user given exponent
CDigFloat sqrt (const CDigFloat &DF)
sqrt: returns CDigFloat as square root of user given value
CDigFloat min (const CDigFloat &one, const CDigFloat &other)
min: returns the smaller CDigFloat
CDigFloat max (const CDigFloat &one, const CDigFloat &other)
max: returns the greater CDigFloat
CDigFloat operator+ (const CDigFloat &One, const CDigFloat &Other)
operator+
CDigFloat operator- (const CDigFloat &One)
operator- for expression "-X" instead of X*(-1)
CDigFloat operator- (const CDigFloat &One, const CDigFloat &Other)
operator-
CDigFloat operator* (const CDigFloat &One, const CDigFloat &Other)
operator*
CDigFloat operator/ (const CDigFloat &One, const CDigFloat &Other)
operator/
Macro Definition Documentation
DF_DEFAULT_PRINT_PRECISION
#define DF_DEFAULT_PRINT_PRECISION 10
Definition at line 38 of file DigFloat.h.
DF_RAW_PRINT_PRECISION
#define DF_RAW_PRINT_PRECISION 40
Definition at line 37 of file DigFloat.h.
Function Documentation
abs()
CDigFloat abs (const CDigFloat & DF)
abs: returns CDigFloat with absolute value;
Parameters
FM CDigFloat
Returns
CDigFloat
Definition at line 302 of file DigFloat.cpp.
References CDigFloat::RawValue().
exp()
CDigFloat exp (const CDigFloat & dfExp)
exp: returns CDigFloat exponential expression to Euler number and user given exponent
Parameters
dfExp CDigFloat as exponent
Returns
CDigFloat
Definition at line 392 of file DigFloat.cpp.
References CDigFloat::dError, CDigFloat::exp, CDigFloat::RawError(), CDigFloat::RawValue(), CDigFloat::ValueMaxLimit(), and CDigFloat::ValueMinLimit().
log()
CDigFloat log (const CDigFloat & DF, const CDigFloat & dfBase = 0)
log: returns CDigFloat logarithm to user given base (default: natural logarithm with base euler number);
Parameters
DF CDigFloat
dfBase CDigFloat as base (optional)
Returns
CDigFloat
Definition at line 309 of file DigFloat.cpp.
References CDigFloat::dError, CDigFloat::Error(), CDigFloat::RawError(), CDigFloat::RawValue(), CDigFloat::ValueMaxLimit(), and CDigFloat::ValueMinLimit().
max()
CDigFloat max (const CDigFloat & one, const CDigFloat & other)
max: returns the greater CDigFloat
Parameters
one CDigFloat to compare with other
other CDigFloat to compare with one
Returns
CDigFloat (one or the other)
Definition at line 427 of file DigFloat.cpp.
min()
CDigFloat min (const CDigFloat & one, const CDigFloat & other)
min: returns the smaller CDigFloat
Parameters
one CDigFloat to compare with other
other CDigFloat to compare with one
Returns
CDigFloat (one or the other)
Definition at line 436 of file DigFloat.cpp.
operator*()
CDigFloat operator* (const CDigFloat & One, const CDigFloat & Other)
operator*
Parameters
One CDigFloat
Other CDigFloat
Returns
CDigFloat
Definition at line 464 of file DigFloat.cpp.
operator+()
CDigFloat operator+ (const CDigFloat & One, const CDigFloat & Other)
operator+
Parameters
One CDigFloat
Other CDigFloat
Returns
CDigFloat
Definition at line 444 of file DigFloat.cpp.
operator-() [1/2]
CDigFloat operator- (const CDigFloat & One)
operator- for expression "-X" instead of X*(-1)
Parameters
One CDigFloat
Other CDigFloat
Returns
CDigFloat
Definition at line 451 of file DigFloat.cpp.
operator-() [2/2]
CDigFloat operator- (const CDigFloat & One, const CDigFloat & Other)
operator-
Parameters
One CDigFloat
Other CDigFloat
Returns
CDigFloat
Definition at line 456 of file DigFloat.cpp.
operator/()
CDigFloat operator/ (const CDigFloat & One, const CDigFloat & Other)
operator/
Parameters
One CDigFloat
Other CDigFloat
Returns
CDigFloat
Definition at line 471 of file DigFloat.cpp.
pow()
CDigFloat pow (const CDigFloat & dfBase, const CDigFloat & dfExp)
pow: returns CDigFloat exponential expression to user given base and exponent
Parameters
dfBase CDigFloat as base
dfExp CDigFloat as exponent
Returns
CDigFloat
Definition at line 373 of file DigFloat.cpp.
References CDigFloat::dError, max(), min(), CDigFloat::pow, CDigFloat::RawError(), CDigFloat::RawValue(), CDigFloat::ValueMaxLimit(), and CDigFloat::ValueMinLimit().
sqrt()
CDigFloat sqrt (const CDigFloat & DF)
sqrt: returns CDigFloat as square root of user given value
Parameters
DF CDigFloat
Returns
CDigFloat
Definition at line 410 of file DigFloat.cpp.
References CDigFloat::dError, CDigFloat::RawError(), CDigFloat::RawValue(), CDigFloat::sqrt, CDigFloat::ValueMaxLimit(), and CDigFloat::ValueMinLimit().