FloatingMeasure: CSimpleMeasure Class Reference
CSimpleMeasure Class Reference
CSimpleMeasure: represents a pre measure combined with a base measure like "mV".
This class offers:
#include <SimpleMeasure.h>
Public Member Functions
CSimpleMeasure ()
Default constructor: calls CSimpleMeasure::_Init()
CSimpleMeasure (const CSimpleMeasure &other)
Copy constructor: calls CSimpleMeasure::_Init() and CSimpleMeasure::SetByID.
CSimpleMeasure (const CSimpleMeasure *other)
Copy constructor: calls CSimpleMeasure::_Init() and CSimpleMeasure::SetByID.
~CSimpleMeasure ()
Destructor.
CSimpleMeasure & operator= (const CSimpleMeasure &other)
Assignment operator: calls CSimpleMeasure::_Init() and CSimpleMeasure::SetByID.
bool const operator== (const CSimpleMeasure &other) const
operator ==:
compares
bool operator!= (const CSimpleMeasure &other) const
operator !=:
calls inverted CSimpleMeasure::operator==
void SetByID (const ePreMeasure PreMeasureEnum, const eBaseMeasure BaseMeasureEnum)
sets the CSimpleMeasure::PreIndex and CSimpleMeasure::BaseIndex
and adapts the depending members
void SetByShort (const string &strPreLabelShort, const string &strBaseLabelShort)
calls CSimpleMeasure::SetByID with the indices defined by the corresponding short labels
void SetByLong (const string &strPreLabelLong, const string &strBaseLabelLong)
calls CSimpleMeasure::SetByID with the indices defined by the corresponding long labels
bool Valid ()
checks if CSimpleMeasure::PreIndex and CSimpleMeasure::BaseIndex are valid indices
defined in ePreMeasure and eBaseMeasure
const string DebugOut ()
prints all members as string for debugging.
bool Compatible (const CSimpleMeasure &other)
check compatiblity with other CSimpleMeasure:
compatibility is given if the CSimpleMeasure::eBaseMeasure have the same SI measure.
const double SIFactor (void)
getter of CSimpleMeasure::dSIFactor
const double SIOffset (void)
getter of CSimpleMeasure::dSIOffset
const string & Short (void)
getter of CSimpleMeasure::strShort
const string & Long (void)
getter of CSimpleMeasure::strLong
const eBaseMeasure BaseID () const
getter of CSimpleMeasure::BaseIndex
const ePreMeasure PreID () const
getter of CSimpleMeasure::PreIndex
Protected Member Functions
void _Init ()
sets CSimpleMeasure::BaseIndex to eBaseMeasure::bmUnknown and CSimpleMeasure::PreIndex to CPreMeasure::pmUnknown
Protected Attributes
eBaseMeasure BaseIndex
index of type eBaseMeasure:
used to get elements from the vectors of BASE:
ePreMeasure PreIndex
index of type ePreMeasure:
used to get elements from the vectors of PRE:
double dSIFactor
factor which must be applied this CSimpleMeasure to achieve SI measure (e.g. mV : SIFactor = 1000).
This factor must be applied in combination with CSimpleMeasure::dSIOffset:
SIMeasure = SIFactor * Measure + SIOffset
double dSIOffset
offset (SI measure) which must added to this CSimpleMeasure to achieve the corresponding SI measure
E.g. °C: SIOffset = +273.15°K
This offset must be applied in combination with CSimpleMeasure::dSIFactor:
SIMeasure = SIFactor * Measure + SIOffset
string * strShort
short label of this CSimpleMeasure:
combination of the pre-measure short label (see PRE::Short)
and the base-measure short label (see BASE::Short)
string * strLong
long label of this CSimpleMeasure:
combination of the pre-measure long label (see PRE::Long)
and the base-measure long label (see BASE::Long)
Friends
class CPreMeasure
class CBaseMeasure
class CSingleton< CPreMeasure >
class CSingleton< CBaseMeasure >
Detailed Description
CSimpleMeasure: represents a pre measure combined with a base measure like "mV".
This class offers:
handling of combined short / long labels of CPreMeasure and CBaseMeasure
construction by short / long labels of CPreMeasure and CBaseMeasure
recalculation offset and factor to SI measure of the CPreMeasure and CBaseMeasure
Definition at line 39 of file SimpleMeasure.h.
Constructor & Destructor Documentation
CSimpleMeasure() [1/3]
CSimpleMeasure::CSimpleMeasure ()
Default constructor: calls CSimpleMeasure::_Init()
Definition at line 28 of file SimpleMeasure.cpp.
References _Init().
CSimpleMeasure() [2/3]
CSimpleMeasure::CSimpleMeasure (const CSimpleMeasure & other)
Copy constructor: calls CSimpleMeasure::_Init() and CSimpleMeasure::SetByID.
Parameters
other instance to copy from
Definition at line 33 of file SimpleMeasure.cpp.
References _Init(), BaseID(), PreID(), and SetByID().
CSimpleMeasure() [3/3]
CSimpleMeasure::CSimpleMeasure (const CSimpleMeasure * other)
Copy constructor: calls CSimpleMeasure::_Init() and CSimpleMeasure::SetByID.
Parameters
other instance to copy from
Definition at line 38 of file SimpleMeasure.cpp.
References _Init(), BaseID(), PreID(), and SetByID().
~CSimpleMeasure()
CSimpleMeasure::~CSimpleMeasure ()
Destructor.
Definition at line 43 of file SimpleMeasure.cpp.
References SecureDeleteObjectPointer(), strLong, and strShort.
Member Function Documentation
_Init()
void CSimpleMeasure::_Init () protected
sets CSimpleMeasure::BaseIndex to eBaseMeasure::bmUnknown and CSimpleMeasure::PreIndex to CPreMeasure::pmUnknown
Definition at line 100 of file SimpleMeasure.cpp.
References BaseIndex, bmUnknown, pmUnknown, PreIndex, strLong, and strShort.
BaseID()
const eBaseMeasure CSimpleMeasure::BaseID () const inline
getter of CSimpleMeasure::BaseIndex
Returns
eBaseMeasure&
Definition at line 184 of file SimpleMeasure.h.
Compatible()
bool CSimpleMeasure::Compatible (const CSimpleMeasure & other) inline
check compatiblity with other CSimpleMeasure:
compatibility is given if the CSimpleMeasure::eBaseMeasure have the same SI measure.
Parameters
other CSimpleMeasure to check for compatibility
Returns
bool
Definition at line 150 of file SimpleMeasure.h.
References BASE, and BaseID().
DebugOut()
const string CSimpleMeasure::DebugOut ()
prints all members as string for debugging.
Returns
const string
Definition at line 88 of file SimpleMeasure.cpp.
References BASE, BaseID(), Long(), PRE, PreID(), Short(), SIFactor(), and SIOffset().
Long()
const string& CSimpleMeasure::Long (void) inline
getter of CSimpleMeasure::strLong
Returns
const string&
Definition at line 178 of file SimpleMeasure.h.
operator!=()
bool CSimpleMeasure::operator!= (const CSimpleMeasure & other) const
operator !=:
calls inverted CSimpleMeasure::operator==
Parameters
other CSimpleMeasure to compare
Returns
const bool
Definition at line 64 of file SimpleMeasure.cpp.
operator=()
CSimpleMeasure & CSimpleMeasure::operator= (const CSimpleMeasure & other)
Assignment operator: calls CSimpleMeasure::_Init() and CSimpleMeasure::SetByID.
Parameters
other instance to assign from
Returns
reference to this
Definition at line 49 of file SimpleMeasure.cpp.
References BaseID(), PreID(), and SetByID().
operator==()
bool const CSimpleMeasure::operator== (const CSimpleMeasure & other) const
operator ==:
compares
CSimpleMeasure::PreIndex
CSimpleMeasure::BaseIndex
Parameters
other CSimpleMeasure to compare
Returns
const bool
Definition at line 57 of file SimpleMeasure.cpp.
References BaseID(), and PreID().
PreID()
const ePreMeasure CSimpleMeasure::PreID () const inline
getter of CSimpleMeasure::PreIndex
Returns
ePreMeasure&
Definition at line 190 of file SimpleMeasure.h.
SetByID()
void CSimpleMeasure::SetByID (const ePreMeasure PreMeasureEnum, const eBaseMeasure BaseMeasureEnum)
sets the CSimpleMeasure::PreIndex and CSimpleMeasure::BaseIndex
and adapts the depending members
CSimpleMeasure::dSIFactor
CSimpleMeasure::dSIOffset
CSimpleMeasure::strShort
CSimpleMeasure::strLong
Parameters
PreMeasureEnum index of ePreMeasure
BaseMeasureEnum index of eBaseMeasure
Definition at line 69 of file SimpleMeasure.cpp.
References BASE, BaseID(), BaseIndex, dSIFactor, dSIOffset, PRE, PreID(), PreIndex, strLong, and strShort.
SetByLong()
void CSimpleMeasure::SetByLong (const string & strPreLabelLong, const string & strBaseLabelLong)
calls CSimpleMeasure::SetByID with the indices defined by the corresponding long labels
Parameters
strPreLabelLong long label searched in CPreMeasure::vstrLong in PRE
strBaseLabelLong long label searched in CPreMeasure::vstrLong in BASE
Definition at line 83 of file SimpleMeasure.cpp.
References BASE, PRE, and SetByID().
SetByShort()
void CSimpleMeasure::SetByShort (const string & strPreLabelShort, const string & strBaseLabelShort)
calls CSimpleMeasure::SetByID with the indices defined by the corresponding short labels
Parameters
strPreLabelShort short label searched in CPreMeasure::vstrShort in PRE
strBaseLabelShort short label searchedin CBaseMeasure::vstrShort in BASE
Definition at line 79 of file SimpleMeasure.cpp.
References BASE, PRE, and SetByID().
Short()
const string& CSimpleMeasure::Short (void) inline
getter of CSimpleMeasure::strShort
Returns
const string&
Definition at line 172 of file SimpleMeasure.h.
SIFactor()
const double CSimpleMeasure::SIFactor (void) inline
getter of CSimpleMeasure::dSIFactor
Returns
const double
Definition at line 160 of file SimpleMeasure.h.
SIOffset()
const double CSimpleMeasure::SIOffset (void) inline
getter of CSimpleMeasure::dSIOffset
Returns
const double
Definition at line 166 of file SimpleMeasure.h.
Valid()
bool CSimpleMeasure::Valid () inline
checks if CSimpleMeasure::PreIndex and CSimpleMeasure::BaseIndex are valid indices
defined in ePreMeasure and eBaseMeasure
Returns
bool, true in case the indices are valid
Definition at line 135 of file SimpleMeasure.h.
References bmFirst, and pmFirst.
Friends And Related Function Documentation
CBaseMeasure
friend class CBaseMeasure friend
Definition at line 46 of file SimpleMeasure.h.
CPreMeasure
friend class CPreMeasure friend
Definition at line 45 of file SimpleMeasure.h.
CSingleton< CBaseMeasure >
friend class CSingleton< CBaseMeasure > friend
Definition at line 48 of file SimpleMeasure.h.
CSingleton< CPreMeasure >
friend class CSingleton< CPreMeasure > friend
Definition at line 47 of file SimpleMeasure.h.
Member Data Documentation
BaseIndex
eBaseMeasure CSimpleMeasure::BaseIndex protected
index of type eBaseMeasure:
used to get elements from the vectors of BASE:
CBaseMeasure::vdOffset
CBaseMeasure::vdFactor
CBaseMeasure::vstrShort
CBaseMeasure::vstrLong
Definition at line 216 of file SimpleMeasure.h.
dSIFactor
double CSimpleMeasure::dSIFactor protected
factor which must be applied this CSimpleMeasure to achieve SI measure (e.g. mV : SIFactor = 1000).
This factor must be applied in combination with CSimpleMeasure::dSIOffset:
SIMeasure = SIFactor * Measure + SIOffset
Definition at line 235 of file SimpleMeasure.h.
dSIOffset
double CSimpleMeasure::dSIOffset protected
offset (SI measure) which must added to this CSimpleMeasure to achieve the corresponding SI measure
E.g. °C: SIOffset = +273.15°K
This offset must be applied in combination with CSimpleMeasure::dSIFactor:
SIMeasure = SIFactor * Measure + SIOffset
Definition at line 244 of file SimpleMeasure.h.
PreIndex
ePreMeasure CSimpleMeasure::PreIndex protected
index of type ePreMeasure:
used to get elements from the vectors of PRE:
CPreMeasure::vdOffset
CPreMeasure::vdFactor
CPreMeasure::vstrShort
CPreMeasure::vstrLong
Definition at line 227 of file SimpleMeasure.h.
strLong
string* CSimpleMeasure::strLong protected
long label of this CSimpleMeasure:
combination of the pre-measure long label (see PRE::Long)
and the base-measure long label (see BASE::Long)
Definition at line 260 of file SimpleMeasure.h.
strShort
string* CSimpleMeasure::strShort protected
short label of this CSimpleMeasure:
combination of the pre-measure short label (see PRE::Short)
and the base-measure short label (see BASE::Short)
Definition at line 252 of file SimpleMeasure.h.
The documentation for this class was generated from the following files:
FloatingMeasure/Measure/SimpleMeasure.h
FloatingMeasure/Measure/SimpleMeasure.cpp