FloatingMeasure: CPreMeasure Class Reference
CPreMeasure Class Reference
CPreMeasure represents the pre-measure part of a measure.
For example milli volt consists of the base-measure part "Volt" (see CBaseMeasure) and the pre-measure part "milli".
This class handles vectors of:
#include <PreMeasure.h>
Public Member Functions
CPreMeasure ()
default constructor: initialize all member vectors of CPreMeasure:
~CPreMeasure ()
Destructor.
string DebugOut (const int nIndex)
returns all representations in a string
string DebugOut (const ePreMeasure PreMeasureEnum)
returns all representations in a string
int Exp10 (const int nExp10Idx)
returns the exp10 (see CPreMeasure::vnExp10) for a given pre-measure
ePreMeasure GetIDByShortLabel (const string &strShortLabel)
returns the enum (index) of the pre-measure by searching the vstrShort
ePreMeasure GetIDByLongLabel (const string &strLongLabel)
returns the enum (index) of the pre-measure by searching the vstrLong
ePreMeasure GetIDByFactor (const double dPreMeasureFactor)
returns the enum (index) of the pre-measure by searching the vdFactor
ePreMeasure GetIDByExp10 (const int nExp10)
returns the enum (index) of the pre-measure by searching the vnExp10
Public Member Functions inherited from CVectorHandle
CVectorHandle ()
does nothing
~CVectorHandle ()
destructor: calls CVectorHandle::_DeInit()
int GetIndexByShortLabel (const string &strShortLabel)
returns the index of the pre-unit if the user given string matches one of the elemens in CPreUnit::m_vstrPreUnitShort
int GetIndexByLongLabel (const string &strLongLabel)
returns the index of the pre-unit if the user given string matches one of the elemens in CPreUnit::m_vstrPreUnitLong
const string & Long (const unsigned int uiIndex)
gets element from CVectorHandle::vstrShort by index
const string & Short (const unsigned int uiIndex)
gets element from CVectorHandle::vstrLong by index
const double Factor (const unsigned int uiIndex)
gets element from CVectorHandle::vdFactor by index
Protected Attributes
vector< int > * vnExp10
the exponents to the base of 10 (exp10 from now on) of the corresponding factors stored in CVectorHandle::vdFactor
Protected Attributes inherited from CVectorHandle
vector< double > * vdFactor
vector keeping all the factors:
e.g.
vector< string > * vstrLong
vector keeping the long label
e.g.
vector< string > * vstrShort
vector keeping the short label:
e.g.
Detailed Description
CPreMeasure represents the pre-measure part of a measure.
For example milli volt consists of the base-measure part "Volt" (see CBaseMeasure) and the pre-measure part "milli".
This class handles vectors of:
pre-measure factor (e.g. for "milli" with index pmMilli the factor is 0.001)
the exponent to the base of 10 of the pre-measure factor (e.g. for "milli" the exp10 is -3)
the short label (e.g. for "milli" the short label is "m")
the long label (e.g. for "milli" the long label is "milli")
These vectors are accessed by the indices defined by the enum ePreMeasure.
The indices can be vice versa accessed by
pre-measure factor
exp10
short label
long label
Definition at line 75 of file PreMeasure.h.
Constructor & Destructor Documentation
CPreMeasure()
CPreMeasure::CPreMeasure ()
default constructor: initialize all member vectors of CPreMeasure:
CPreMeasure::vdFactor
CPreMeasure::vnExp10
CPreMeasure::vstrShort
CPreMeasure::vstrLong
Definition at line 27 of file PreMeasure.cpp.
References INVALID_EXPONENT, mu, pmCenti, pmDeca, pmDeci, pmExa, pmFemto, pmGiga, pmHecto, pmIdent, pmKilo, pmLast, pmMega, pmMicro, pmMilli, pmNano, pmPeta, pmPiko, pmTera, pmUnknown, pmYotta, pmZetta, UNKNOWN_LONG, UNKNOWN_SHORT, CVectorHandle::vdFactor, vnExp10, CVectorHandle::vstrLong, and CVectorHandle::vstrShort.
~CPreMeasure()
CPreMeasure::~CPreMeasure ()
Destructor.
Definition at line 135 of file PreMeasure.cpp.
References SecureDeleteObjectPointer(), and vnExp10.
Member Function Documentation
DebugOut() [1/2]
string CPreMeasure::DebugOut (const int nIndex)
returns all representations in a string
Returns
string: output string
Definition at line 200 of file PreMeasure.cpp.
References CVectorHandle::Factor(), CVectorHandle::Long(), and CVectorHandle::Short().
DebugOut() [2/2]
string CPreMeasure::DebugOut (const ePreMeasure PreMeasureEnum)
returns all representations in a string
Parameters
PreMeasureEnum p_PreMeasureEnum:...
Returns
string
Definition at line 207 of file PreMeasure.cpp.
References DebugOut().
Exp10()
int CPreMeasure::Exp10 (const int nExp10Idx) inline
returns the exp10 (see CPreMeasure::vnExp10) for a given pre-measure
Parameters
nExp10Idx p_nExp10Idx: is e.g. ePreMeasure::pmMilli (returns -3 in this case)
Returns
int
Definition at line 129 of file PreMeasure.h.
References GetElementFromVectorByIndex().
GetIDByExp10()
ePreMeasure CPreMeasure::GetIDByExp10 (const int nExp10)
returns the enum (index) of the pre-measure by searching the vnExp10
Parameters
nExp10 ${p_nExp10:...}
Returns
ePreMeasure
Definition at line 183 of file PreMeasure.cpp.
References abs(), Exp10(), pmFirst, and vnExp10.
GetIDByFactor()
ePreMeasure CPreMeasure::GetIDByFactor (const double dPreMeasureFactor)
returns the enum (index) of the pre-measure by searching the vdFactor
Parameters
dPreMeasureFactor p_dPreMeasureFactor: user given factor (e.g. 0.001 returns ePreMeasure::pmMilli)
Returns
ePreMeasure
Definition at line 142 of file PreMeasure.cpp.
References CVectorHandle::Factor(), pmFirst, pmLast, pmUnknown, and CVectorHandle::vdFactor.
GetIDByLongLabel()
ePreMeasure CPreMeasure::GetIDByLongLabel (const string & strLongLabel) inline
returns the enum (index) of the pre-measure by searching the vstrLong
Parameters
strLongLabel long label of the enum (e.g. "milli"
Returns
ePreMeasure: the pre-measure index (e.g. ePreMeasure::pmMilli)
Definition at line 154 of file PreMeasure.h.
References CVectorHandle::GetIndexByLongLabel().
GetIDByShortLabel()
ePreMeasure CPreMeasure::GetIDByShortLabel (const string & strShortLabel) inline
returns the enum (index) of the pre-measure by searching the vstrShort
Parameters
strShortLabel short label of the enum (e.g. "m" returns ePreMeasure::pmMilli)
Returns
ePreMeasure
Definition at line 143 of file PreMeasure.h.
References CVectorHandle::GetIndexByShortLabel().
Member Data Documentation
vnExp10
vector<int>* CPreMeasure::vnExp10 protected
the exponents to the base of 10 (exp10 from now on) of the corresponding factors stored in CVectorHandle::vdFactor
Definition at line 182 of file PreMeasure.h.
The documentation for this class was generated from the following files:
FloatingMeasure/Measure/PreMeasure.h
FloatingMeasure/Measure/PreMeasure.cpp